[global]
server_name = "CONDUIT_SERVER_NAME_PLACEHOLDER"
database_path = "/var/lib/matrix-conduit/"
database_backend = "rocksdb"
port = 6167
max_request_size = 20_000_000
allow_registration = false
allow_federation = true
allow_check_for_updates = true
trusted_servers = ["matrix.org"]
log = "warn,rocket::launch=info,_=off,sled=off"
