services:
  plane-db:
    security_opt:
      - label=disable
  plane-redis:
    security_opt:
      - label=disable
  plane-mq:
    security_opt:
      - label=disable
  plane-minio:
    security_opt:
      - label=disable
  plane-api:
    security_opt:
      - label=disable
    depends_on:
      - plane-db
      - plane-redis
  plane-worker:
    security_opt:
      - label=disable
    depends_on:
      - plane-db
      - plane-redis
  plane-beat:
    security_opt:
      - label=disable
    depends_on:
      - plane-db
      - plane-redis
  plane-web:
    security_opt:
      - label=disable
  plane-proxy:
    security_opt:
      - label=disable
