apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: landing
  namespace: apps
spec:
  parentRefs:
    - name: homeserver-gateway
      namespace: infra
  hostnames:
    - "landing.k8s.local"
  rules:
    - backendRefs:
        - name: landing
          port: 80
