services:
  gitea-db:
    security_opt:
      - label=disable
  gitea:
    security_opt:
      - label=disable
    depends_on:
      - gitea-db
  gitea-runner:
    security_opt:
      - label=disable
