services:
  forgejo-db:
    security_opt:
      - label=disable
  forgejo:
    security_opt:
      - label=disable
    depends_on:
      - forgejo-db
  forgejo-runner:
    security_opt:
      - label=disable
