services:
  nextcloud-db:
    security_opt:
      - label=disable
  nextcloud:
    security_opt:
      - label=disable
    depends_on:
      - nextcloud-db
      - nextcloud-redis
  nextcloud-cron:
    security_opt:
      - label=disable
