services:
  immich-server:
    security_opt:
      - label=disable
    depends_on:
      - immich-redis
      - immich-database
  immich-machine-learning:
    security_opt:
      - label=disable
  immich-redis:
    security_opt:
      - label=disable
  immich-database:
    security_opt:
      - label=disable
  immich-offline-remover:
    security_opt:
      - label=disable
