services:
  headscale:
    image: headscale/headscale:v0.29
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - ./config:/etc/headscale
      - ${DATA_ROOT}/data:/var/lib/headscale
    networks:
      - homeserver

  headscale-admin:
    image: goodieshq/headscale-admin:v0.27
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      - homeserver

networks:
  homeserver:
    external: true
