#!/usr/bin/env python3
"""Create and drive the kind test cluster that runs the generated manifests.

    uv run kubernetes/cluster.py create            # kind cluster from cluster/kind-config.template.yaml + kubernetes/.env
    uv run kubernetes/cluster.py install           # Gateway API, namespaces, Traefik, storage classes, DB operators
    uv run kubernetes/cluster.py secrets [svc...]  # services/<svc>/.env -> Secret <svc>-env; root .env -> ConfigMap
    uv run kubernetes/cluster.py apply   [svc...]  # kubectl apply -k kubernetes/generated/envs/<env>/<svc>
    uv run kubernetes/cluster.py import  <svc...> [--snapshot TS]  # copy a Compose snapshot's data into the cluster
    uv run kubernetes/cluster.py images  <svc...>  # build a service's local images (Compose build:) and load them into kind
    uv run kubernetes/cluster.py smoke   <svc...> [--keep]  # start with empty data on test hostnames, check, remove
    uv run kubernetes/cluster.py rmi     <svc...>  # remove a stopped service's images from the kind node (frees disk)
    uv run kubernetes/cluster.py validate [svc...]   # server-side dry run: the API server checks every manifest, nothing is created
    uv run kubernetes/cluster.py status
    uv run kubernetes/cluster.py delete            # remove the kind cluster (host data folders are kept)

Defaults to all ported services (kubernetes/scope.yaml) and --env test.
Versions come from kubernetes/versions.env, host paths/ports from
kubernetes/.env. Secrets are built in memory from each service's .env and
piped to kubectl: never written to disk or git. Guide: docs/17.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import string
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import yaml

K8S = Path(__file__).resolve().parent
REPO = K8S.parent
sys.path.insert(0, str(K8S))
from generate import load_compose, load_env, load_overrides, load_scope, own_db_keys, own_mariadb, own_postgres, shared_db_apps, slug  # noqa: E402

VERSIONS = load_env(K8S / "versions.env")
NAMESPACE = "apps"
TEST_DOMAIN = "k8s.local"


def cfg() -> dict[str, str]:
    env = K8S / ".env"
    if not env.is_file():
        sys.exit("kubernetes/.env missing: cp kubernetes/.env.example kubernetes/.env and adjust the paths")
    return {**VERSIONS, **load_env(env)}


def run(cmd: list[str], input: str | None = None, check: bool = True) -> subprocess.CompletedProcess:
    print("+ " + " ".join(cmd[:8]) + (" ..." if len(cmd) > 8 else ""), flush=True)
    return subprocess.run(cmd, input=input, text=True, check=check)


def kubectl(*args: str, input: str | None = None, check: bool = True) -> subprocess.CompletedProcess:
    return run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", *args], input=input, check=check)


def services(names: list[str]) -> list[str]:
    ported = load_scope().get("ported") or []
    bad = [n for n in names if n not in ported]
    if bad:
        sys.exit(f"not ported yet (kubernetes/scope.yaml): {', '.join(bad)}")
    return names or ported


def encryption_config(c: dict) -> None:
    """Write the API server's EncryptionConfiguration (secretbox) with this
    cluster's key: generated once into kubernetes/.env (mode 600, never in
    git), written owner-only to K8S_ENCRYPTION_DIR, mounted into the node."""
    env_file = K8S / ".env"
    key = c.get("K8S_SECRETS_ENCRYPTION_KEY", "")
    if not key:
        import base64, secrets as _secrets
        key = base64.b64encode(_secrets.token_bytes(32)).decode()
        with env_file.open("a") as f:
            f.write("\n# Secrets-at-rest key (secretbox, 32 bytes, base64). Generated by cluster.py create;\n"
                    "# losing it makes the cluster's stored Secrets unreadable (they're rebuilt from .env).\n"
                    f"K8S_SECRETS_ENCRYPTION_KEY={key}\n")
        env_file.chmod(0o600)
        print("generated K8S_SECRETS_ENCRYPTION_KEY in kubernetes/.env")
    d = Path(os.path.expanduser(c["K8S_ENCRYPTION_DIR"]))
    d.mkdir(parents=True, exist_ok=True)
    d.chmod(0o700)
    f = d / "config.yaml"
    f.write_text(yaml.safe_dump({
        "apiVersion": "apiserver.config.k8s.io/v1", "kind": "EncryptionConfiguration",
        "resources": [{"resources": ["secrets"], "providers": [
            {"secretbox": {"keys": [{"name": "key1", "secret": key}]}},
            {"identity": {}},  # reads anything written before encryption was on
        ]}]}))
    f.chmod(0o600)


def cmd_create(_a) -> None:
    c = cfg()
    for key in ("K8S_FAST_PATH", "K8S_BULK_PATH", "K8S_IMAGES_PATH"):
        Path(c[key]).mkdir(parents=True, exist_ok=True)
    encryption_config(c)
    text = string.Template((K8S / "cluster/kind-config.template.yaml").read_text()).substitute(c)
    # Host folders services read from (overrides with hostPath + env): the
    # real path from that service's .env, at the fixed node path the
    # generated manifests use. kind can only add mounts at create time.
    # Compose's localhost ports (generated/host-ports.yaml), on 127.0.0.1 like Compose's prod files.
    hp = yaml.safe_load((K8S / "generated/host-ports.yaml").read_text()) or []
    text = text.replace("    extraMounts:\n", "".join(
        f"      - containerPort: {e['node']}\n        hostPort: {e['host']}\n        listenAddress: \"127.0.0.1\"\n"
        f"        protocol: {e['protocol'].upper()}\n" for e in hp) + "    extraMounts:\n", 1)
    ports = node_ports()
    if ports:
        # Ports host-network services receive straight from outside (the
        # WireGuard VPN): forwarded from every host interface into the node.
        maps = "".join(f"      - containerPort: {pt}\n        hostPort: {pt}\n        protocol: {proto.upper()}\n"
                       for pt, proto in ports)
        text = text.replace("    extraMounts:\n", maps + "    extraMounts:\n", 1)
    for node_path, host, ro in host_mounts():
        text += (f"      - hostPath: {host}\n        containerPath: {node_path}\n"
                 + ("        readOnly: true\n" if ro else ""))
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as f:
        f.write(text)
    try:
        run(["kind", "create", "cluster", "--config", f.name, "--wait", "300s"])
    finally:
        os.unlink(f.name)


def host_mounts() -> list[tuple[str, str, bool]]:
    """[(node path, host path, read-only)] from every ported service's
    overrides; the host path is the .env value Compose uses. Read-only into
    the node only if every container mounting it is :ro in Compose (e.g.
    nextcloud writes OS_ISO_ROOT, nextcloud-cron only reads it)."""
    out: dict[str, tuple[str, bool]] = {}
    for svc in load_scope().get("ported") or []:
        compose = load_compose(svc)["services"]
        for cname, co in (load_overrides(svc).get("containers") or {}).items():
            s = next((s for n, s in compose.items() if (s.get("container_name") or n) == cname), {})
            for tgt, mo in (co.get("mounts") or {}).items():
                if mo.get("hostPath") and mo.get("env"):
                    host = host_path(svc, mo["env"])
                    if not Path(host).is_dir():
                        sys.exit(f"{svc}: {mo['env']}={host} is not a folder on this host")
                    ro = any(m.get("target") == tgt and m.get("read_only") for m in s.get("volumes") or [])
                    prev = out.get(mo["hostPath"], (host, True))
                    out[mo["hostPath"]] = (host, prev[1] and ro)
    return [(k, v[0], v[1]) for k, v in sorted(out.items())]


def node_ports() -> list[tuple[int, str]]:
    """[(port, protocol)] from every ported service's overrides (node_ports)."""
    out = set()
    for svc in load_scope().get("ported") or []:
        for co in (load_overrides(svc).get("containers") or {}).values():
            for np in co.get("node_ports") or []:
                out.add((int(np["port"]), np.get("protocol", "tcp")))
    return sorted(out)


def host_path(svc: str, key: str) -> str:
    """A path from services/<svc>/.env, resolved like Compose does (relative
    to the service folder)."""
    val = load_env(REPO / "services" / svc / ".env").get(key, "")
    if not val:
        sys.exit(f"{svc}: {key} isn't set in services/{svc}/.env")
    return str((REPO / "services" / svc / val).resolve())


def cmd_install(_a) -> None:
    v = VERSIONS
    kubectl("apply", "--server-side", "-f",
            f"https://github.com/kubernetes-sigs/gateway-api/releases/download/{v['GATEWAY_API_VERSION']}/standard-install.yaml")
    kubectl("apply", "-f", str(K8S / "cluster/namespaces.yaml"))
    run(["helm", "--kube-context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "upgrade", "--install", "traefik", "traefik",
         "--repo", "https://traefik.github.io/charts", "--version", v["TRAEFIK_CHART_VERSION"],
         "--namespace", "infra", "-f", str(K8S / "cluster/traefik/values.yaml"), "--wait", "--timeout", "5m"])
    # kind's local-path provisioner: allow the fast/bulk folders, then the classes.
    conf = {"nodePathMap": [{"node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                             "paths": ["/var/local-path-provisioner", "/var/k8s/fast", "/var/k8s/bulk"]}]}
    kubectl("-n", "local-path-storage", "patch", "configmap", "local-path-config", "--type", "merge",
            "-p", json.dumps({"data": {"config.json": json.dumps(conf, indent=1)}}))
    kubectl("apply", "-f", str(K8S / "cluster/storage.yaml"))
    # The node holding the host folders (kind: its only node); on a real
    # cluster, label the machine that has them instead.
    kubectl("label", "nodes", "--all", "homeserver/host-folders=true", "--overwrite")
    # Database operators: CloudNativePG (shared + own Postgres) and
    # mariadb-operator (shared MariaDB). Both watch every namespace.
    kubectl("apply", "--server-side", "-f",
            f"https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v{v['CNPG_VERSION']}/cnpg-{v['CNPG_VERSION']}.yaml")
    kubectl("-n", "cnpg-system", "rollout", "status", "deployment/cnpg-controller-manager", "--timeout=5m")
    for chart in ("mariadb-operator-crds", "mariadb-operator"):
        run(["helm", "--kube-context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "upgrade", "--install", chart, chart,
             "--repo", "https://helm.mariadb.com/mariadb-operator", "--version", v["MARIADB_OPERATOR_VERSION"],
             "--namespace", "mariadb-operator", "--create-namespace", "--wait", "--timeout", "5m"])


def env_hash(data: dict[str, str]) -> str:
    return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()


def secret_manifest(name: str, data: dict[str, str], kind: str = "Opaque", labels: dict | None = None) -> str:
    return yaml.safe_dump({"apiVersion": "v1", "kind": "Secret", "type": kind,
                           "metadata": {"name": name, "namespace": NAMESPACE,
                                        "labels": {"app.kubernetes.io/part-of": "homeserver", **(labels or {})},
                                        "annotations": {"homeserver/env-sha256": env_hash(data)}},
                           "stringData": data})


def current_hash(name: str) -> str | None:
    """The env hash on the Secret in the cluster, or None if it doesn't exist."""
    p = subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "get", "secret",
                        name, "-o", "jsonpath={.metadata.annotations.homeserver/env-sha256}"],
                       capture_output=True, text=True)
    return p.stdout.strip() if p.returncode == 0 else None


def basic_auth(name: str, user: str, password: str) -> str:
    """CNPG reads logins from kubernetes.io/basic-auth Secrets; the reload
    label makes it apply a changed password (rotation = edit .env, re-run)."""
    return secret_manifest(name, {"username": user, "password": password},
                           "kubernetes.io/basic-auth", {"cnpg.io/reload": "true"})


def cmd_secrets(a) -> None:
    root = load_env(REPO / ".env")
    if a.env == "test":
        root["DOMAIN"] = TEST_DOMAIN  # apps build their own links for the test hostnames
    cm = {"apiVersion": "v1", "kind": "ConfigMap",
          "metadata": {"name": "homeserver-root", "namespace": NAMESPACE},
          "data": {"DOMAIN": root.get("DOMAIN", ""), "TZ": root.get("TZ", "Asia/Kolkata")}}
    kubectl("apply", "-f", "-", input=yaml.safe_dump(cm))
    prod_only = set(load_scope().get("prod_only") or [])
    for svc in services(a.services):
        env_file = REPO / "services" / svc / ".env"
        if a.env == "test" and svc in prod_only:
            continue  # e.g. cloudflared: its tunnel token never goes to the test cluster
        if not env_file.is_file():
            continue
        env = load_env(env_file)
        spec = shared_db_apps().get(svc)
        # mariadb-operator re-reads a password Secret only when it carries
        # this label (User.passwordSecretKeyRef docs), so rotation = edit .env.
        watch = {"k8s.mariadb.com/watch": ""} if svc == "shared-mariadb" or (spec and spec["engine"] == "mariadb") else None
        before = current_hash(f"{svc}-env")
        kubectl("apply", "-f", "-", input=secret_manifest(f"{svc}-env", env, labels=watch))
        # (Operator-run servers are left to their operator.)
        if before and before != env_hash(env) and svc not in ("shared-postgres", "shared-mariadb"):
            # Pods read env only at start: restart this service's workloads,
            # the kubectl form of Helm's documented checksum/config roll.
            kubectl("rollout", "restart", "deployment,statefulset,daemonset", "-n", NAMESPACE,
                    "-l", f"homeserver/service={svc}", check=False)
        if svc == "shared-postgres":
            kubectl("apply", "-f", "-", input=basic_auth(f"{svc}-superuser", env.get("POSTGRES_USER", "postgres"),
                                                         env.get("POSTGRES_PASSWORD", "")))
        if (own := own_db_keys(svc)):
            # A CORE app's own CNPG cluster: its database owner login.
            # (<svc>-db-superuser for apps that log in as postgres.)
            user = env.get(own["user_key"], own["user"]) if own["user_key"] else own["user"]
            kubectl("apply", "-f", "-", input=basic_auth(own["secret"], user, env.get(own["password_key"], "")))
        if spec and spec["engine"] == "postgres":
            # Same values homeserver.py's shared_db_creds reads from this .env.
            val = lambda k: k[1:] if k.startswith("=") else env.get(k, "")  # noqa: E731
            kubectl("apply", "-f", "-", input=basic_auth(f"{svc}-db-role", val(spec["user_key"]),
                                                         val(spec["password_key"])))


def cmd_apply(a) -> None:
    for svc in services(a.services):
        d = K8S / "generated/envs" / a.env / svc
        if not d.is_dir():
            print(f"skip {svc}: not rendered for env {a.env}")
            continue
        kubectl("apply", "-k", str(d))


def snapshot_dir(svc: str, ts: str | None) -> Path | None:
    """The service's newest regular Compose snapshot (timestamp-named folders
    only, as homeserver.py's restore picks them), or the one asked for."""
    root = REPO / "service_data/backup" / svc
    snaps = sorted(d.name for d in root.glob("*") if d.is_dir() and d.name[:8].isdigit()) if root.is_dir() else []
    if ts:
        if ts not in snaps and not (root / ts).is_dir():
            sys.exit(f"{svc}: no snapshot {ts} in {root}")
        return root / ts
    if not snaps:
        return None  # e.g. clamav: no data, only copy_from folders
    return root / snaps[-1]


def pvc_host_path(pvc: str) -> Path:
    """Host folder behind a bound PVC (kind node paths -> kubernetes/.env paths)."""
    c = cfg()
    p = subprocess.run(["kubectl", "--context", f"kind-{c['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "get", "pvc", pvc,
                        "-o", "jsonpath={.spec.volumeName}"], capture_output=True, text=True)
    pv = p.stdout.strip()
    if not pv:
        sys.exit(f"PVC {pvc} isn't bound yet: apply the service first and let its pod start once")
    q = subprocess.run(["kubectl", "--context", f"kind-{c['K8S_CLUSTER_NAME']}", "get", "pv", pv, "-o",
                        "jsonpath={.spec.hostPath.path}{.spec.local.path}"], capture_output=True, text=True)
    node = q.stdout.strip()
    for prefix, key in (("/var/k8s/fast", "K8S_FAST_PATH"), ("/var/k8s/bulk", "K8S_BULK_PATH")):
        if node.startswith(prefix):
            return Path(os.path.expanduser(c[key])) / node[len(prefix):].lstrip("/")
    sys.exit(f"PV {pv} lives at {node}, outside the fast/bulk folders")


def has_pvc(svc: str, name: str) -> bool:
    """Whether the generated manifests declare this PVC for the service."""
    f = K8S / "generated/apps" / svc / "storage.yaml"
    return f.is_file() and any(d and d["metadata"]["name"] == name for d in yaml.safe_load_all(f.read_text()))


def scale(svc: str, replicas: int) -> None:
    sel = f"homeserver/service={svc}"
    kubectl("scale", "deployment", "-n", NAMESPACE, "-l", sel, f"--replicas={replicas}", check=False)
    if replicas == 0:
        # Wait for the Deployments' pods only (DaemonSets can't scale to 0).
        names = subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "get",
                                "deployment", "-l", sel, "-o", "jsonpath={.items[*].metadata.name}"],
                               capture_output=True, text=True).stdout.split()
        for name in names:
            kubectl("wait", "--for=delete", "pod", "-n", NAMESPACE, "-l", f"app.kubernetes.io/name={name}",
                    "--timeout=180s", check=False)


def cmd_import(a) -> None:
    """Copy a Compose snapshot into the test cluster: never the live
    service_data folders, so Docker's data is only ever read. --live-db takes
    own Postgres databases from the running Compose container instead
    (pg_dump, read-only), for when the newest snapshot is older than the data."""
    global LIVE_DB
    LIVE_DB = a.live_db
    for svc in services(a.services):
        snap = snapshot_dir(svc, a.snapshot)
        print(f"== {svc}: " + (f"snapshot {snap.name}" if snap else "no snapshot (homeserver.py takes one on every 'down'); copy_from folders only"))
        data_tar = next(snap.glob("service_data_*.tar.gz"), None) if snap else None
        scale(svc, 0)
        if data_tar and has_pvc(svc, f"{svc}-data"):
            unpack(data_tar, pvc_host_path(f"{svc}-data"))
        elif data_tar:
            # No DATA_ROOT mount in Compose (e.g. guacamole keeps everything
            # in its database); the snapshot's tar should be empty.
            files = [n for n in subprocess.run(["tar", "tzf", str(data_tar)], capture_output=True, text=True).stdout.split()
                     if not n.endswith("/")]
            if files:
                print(f"note: {svc} has no data volume; skipped {len(files)} file(s) in {data_tar.name}", flush=True)
        # Host folders Compose keeps outside DATA_ROOT (copy_from overrides).
        for co in (load_overrides(svc).get("containers") or {}).values():
            for mo in (co.get("mounts") or {}).values():
                if mo.get("volume") and mo.get("copy_from"):
                    copy_folder(Path(host_path(svc, mo["copy_from"])), pvc_host_path(f"{svc}-{slug(mo['volume'])}"))
        for vol_tar in sorted(snap.glob(f"{svc}_*.tar.gz")) if snap else []:
            import_volume(svc, vol_tar)
        scale(svc, 1)
        # DaemonSets can't scale to 0: restart them to pick up the restored files.
        kubectl("rollout", "restart", "daemonset", "-n", NAMESPACE, "-l", f"homeserver/service={svc}", check=False)


LIVE_DB = False


def as_root(mounts: list[str], script: str) -> None:
    """Run a shell script as root in a throwaway container (no network), so
    copies keep every file's owner (postgres 999, clickhouse 101, ...)."""
    args = ["docker", "run", "--rm", "--network", "none"]
    for m in mounts:
        args += ["-v", m]
    run(args + [VERSIONS["WAIT_IMAGE"], "sh", "-c", script])


def unpack(tar: Path, dest: Path) -> None:
    """Replace a volume folder's contents with a snapshot tar's."""
    as_root([f"{tar}:/in.tgz:ro", f"{dest}:/dst"],
            "find /dst -mindepth 1 -maxdepth 1 -exec rm -rf {} + && tar xzf /in.tgz -C /dst")


def copy_folder(src: Path, dest: Path) -> None:
    """Copy a host folder into a volume folder (owners and times kept)."""
    if not src.is_dir():
        sys.exit(f"copy_from source {src} is not a folder")
    print(f"+ copy {src} -> {dest}", flush=True)
    as_root([f"{src}:/src:ro", f"{dest}:/dst"],
            "find /dst -mindepth 1 -maxdepth 1 -exec rm -rf {} + && cp -a /src/. /dst/")


def restore_pg(cname: str, db: str, user: str, dump: Path) -> None:
    """Load a pg_dump into the CNPG cluster: recreate the database owned by
    the app's role, create the dump's extensions as superuser (an app role
    may not), then restore everything else as the app's role
    (pg_restore -L with the EXTENSION entries left out)."""
    pod = f"{cname}-1"  # CNPG names the first instance <cluster>-1
    kubectl("wait", "-n", NAMESPACE, "--for=condition=Ready", f"cluster/{cname}", "--timeout=300s")
    ctx = ["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "exec", "-i", pod, "-c", "postgres", "--"]
    toc = subprocess.run(ctx + ["sh", "-c", "cat > /controller/restore.dump && pg_restore -l /controller/restore.dump"],
                         stdin=dump.open("rb"), capture_output=True, check=True).stdout.decode()
    # TOC lines look like "4185; 3079 16384 EXTENSION - vchord" (+ owner, if any)
    exts = sorted({m.group(1) for ln in toc.splitlines() if not ln.startswith(";")
                   for m in [re.search(r" EXTENSION - (\S+)", ln)] if m})
    keep = "\n".join(ln for ln in toc.splitlines() if " EXTENSION - " not in ln and " COMMENT - EXTENSION " not in ln)
    sql = (f'DROP DATABASE IF EXISTS "{db}" WITH (FORCE);\nCREATE DATABASE "{db}" OWNER "{user}";\n')
    subprocess.run(ctx + ["psql", "-v", "ON_ERROR_STOP=1", "-d", "postgres"], input=sql.encode(), check=True)
    if exts:
        subprocess.run(ctx + ["psql", "-v", "ON_ERROR_STOP=1", "-d", db], check=True,
                       input="".join(f'CREATE EXTENSION IF NOT EXISTS "{e}" CASCADE;\n' for e in exts).encode())
    print(f"+ pg_restore into {pod} ({db}, owned by {user}; extensions: {', '.join(exts) or 'none'})", flush=True)
    subprocess.run(ctx + ["sh", "-c", f"cat > /controller/restore.list && pg_restore --no-owner --role={user} "
                                      f"-L /controller/restore.list -d {db} /controller/restore.dump; "
                                      "rc=$?; rm -f /controller/restore.dump /controller/restore.list; exit $rc"],
                   input=keep.encode(), check=False)


def import_mariadb(svc: str, owner: tuple, vol: str, vol_tar: Path, mdb: dict) -> None:
    """Own MariaDB volume -> mariadb-dump -> the operator's MariaDB: from a
    throwaway container of the Compose image on the unpacked snapshot, or
    (--live-db) from the running Compose container."""
    n, s = owner
    cname = s.get("container_name") or n
    env = load_env(REPO / "services" / svc / ".env")
    root_pw = env.get(mdb["spec"]["rootPasswordSecretKeyRef"]["key"], "")
    db = mdb["spec"]["database"]
    with tempfile.TemporaryDirectory(prefix=f"k8s-import-{svc}-") as tmp:
        dump = Path(tmp) / "db.sql"
        src = cname
        if not LIVE_DB:
            data = Path(tmp) / "data"
            data.mkdir()
            run(["tar", "xzf", str(vol_tar), "-C", str(data), "--no-same-owner"])
            src = f"k8s-import-{svc}"
            mount = next(m["target"] for m in s["volumes"] if str(m.get("source")) == vol)
            run(["docker", "run", "-d", "--rm", "--name", src, "--network", "none", "--user", f"{os.getuid()}:{os.getgid()}",
                 "-v", f"{data}:{mount}", s["image"]])
        try:
            for _ in range(60):
                if subprocess.run(["docker", "exec", "-e", f"MYSQL_PWD={root_pw}", src, "mariadb-admin", "-uroot", "ping"],
                                  capture_output=True).returncode == 0:
                    break
                time.sleep(2)
            else:
                sys.exit(f"{svc}: MariaDB source {src} didn't answer")
            print(f"+ mariadb-dump {db} from {src}" + (" (running Compose container, read-only)" if LIVE_DB else ""), flush=True)
            with dump.open("wb") as f:
                subprocess.run(["docker", "exec", "-e", f"MYSQL_PWD={root_pw}", src, "mariadb-dump", "-uroot",
                                "--single-transaction", "--routines", "--triggers", db], stdout=f, check=True)
        finally:
            if not LIVE_DB:
                subprocess.run(["docker", "stop", src], capture_output=True)
        kubectl("wait", "-n", NAMESPACE, "--for=condition=Ready", f"mariadb/{cname}", "--timeout=300s")
        print(f"+ load into {cname}-0 ({db})", flush=True)
        with dump.open("rb") as f:
            subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "exec", "-i",
                            f"{cname}-0", "--", "sh", "-c", f'mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" {db}'],
                           stdin=f, check=True)


def import_volume(svc: str, vol_tar: Path) -> None:
    """A named-volume tar from the snapshot. An own Postgres volume is loaded
    with pg_dump/pg_restore (CNPG can't adopt a raw data folder): the tar is
    unpacked into scratch space, served by a throwaway container of the
    Compose image (no network), dumped, and restored into the CNPG cluster.
    Any other named volume is unpacked into its PVC."""
    compose = load_compose(svc)
    vol = vol_tar.name[len(svc) + 1:].rsplit("_", 1)[0].removeprefix(f"{svc}_")
    owner = next(((n, s) for n, s in compose["services"].items()
                  if any(str(m.get("source")) == vol for m in s.get("volumes") or [])), None)
    if owner and own_postgres(svc, owner[0], owner[1], load_overrides(svc)):
        n, s = owner
        cname = s.get("container_name") or n
        env = load_env(REPO / "services" / svc / ".env")
        own = own_db_keys(svc)
        db = own["db"]
        user = env.get(own["user_key"], own["user"]) if own["user_key"] else own["user"]
        with tempfile.TemporaryDirectory(prefix=f"k8s-import-{svc}-") as tmp:
            dump = Path(tmp) / "db.dump"
            if LIVE_DB:
                # pg_dump reads one consistent snapshot of the running
                # database without blocking it (PostgreSQL docs, "SQL Dump"):
                # read-only for Compose, which keeps running.
                print(f"+ pg_dump from the running {cname} (read-only)", flush=True)
                with dump.open("wb") as f:
                    subprocess.run(["docker", "exec", cname, "pg_dump", "-Fc", "-U", user, "-d", db], stdout=f, check=True)
                restore_pg(cname, db, user, dump)
                return
            pgdata = Path(tmp) / "pg"
            pgdata.mkdir()
            run(["tar", "xzf", str(vol_tar), "-C", str(pgdata), "--no-same-owner"])
            name = f"k8s-import-{svc}"
            mount = next(m["target"] for m in s["volumes"] if str(m.get("source")) == vol)
            run(["docker", "run", "-d", "--rm", "--name", name, "--network", "none", "--user", f"{os.getuid()}:{os.getgid()}",
                 "-v", f"{pgdata}:{mount}", s["image"]])
            try:
                for _ in range(60):
                    if subprocess.run(["docker", "exec", name, "pg_isready", "-U", user, "-d", db],
                                      capture_output=True).returncode == 0:
                        break
                    time.sleep(2)
                else:
                    sys.exit(f"{svc}: the throwaway Postgres didn't start; see `docker logs {name}`")
                with dump.open("wb") as f:
                    subprocess.run(["docker", "exec", name, "pg_dump", "-Fc", "-U", user, "-d", db], stdout=f, check=True)
            finally:
                subprocess.run(["docker", "stop", name], capture_output=True)
            restore_pg(cname, db, user, dump)
        return
    if owner and (mdb := own_mariadb(svc, owner[0], owner[1], {})):
        import_mariadb(svc, owner, vol, vol_tar, mdb)
        return
    unpack(vol_tar, pvc_host_path(f"{svc}-{slug(vol)}"))


def cmd_validate(a) -> None:
    """Server-side dry run of each service's manifests: the API server checks
    schemas, operator CRDs and field values without creating anything, and
    warns about deprecated APIs or fields, which fail the check too."""
    bad, pss = [], set()
    names = services(a.services)
    for svc in names:
        d = K8S / "generated/envs" / a.env / svc
        if not d.is_dir():
            continue
        p = subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "apply", "--dry-run=server",
                            "-k", str(d)], capture_output=True, text=True)
        warnings = [l for l in p.stderr.splitlines() if l.startswith("Warning")]
        deprecated = [w for w in warnings if "deprecat" in w.lower()]
        pss.update(svc for w in warnings if "PodSecurity" in w)
        if p.returncode != 0 or deprecated:
            bad.append(svc)
            errors = [l for l in p.stderr.splitlines() if l.strip() and not l.startswith("Warning")]
            print(f"FAIL {svc}: " + " | ".join(errors + deprecated)[:500])
    print(f"{len(names) - len(bad)}/{len(names)} pass the server-side dry run (errors and deprecated APIs/fields fail it)")
    if pss:
        print(f"Pod Security warnings (known exceptions, docs/17): {len(pss)} service(s)")
    if bad:
        sys.exit(1)


def cmd_images(a) -> None:
    """Services whose Compose builds an image (build:): build it with Compose
    and load it into the kind node, which can't pull a local-only image."""
    for svc in services(a.services):
        d = REPO / "services" / svc
        compose = load_compose(svc)
        built = [(n, s["image"]) for n, s in compose["services"].items() if s.get("build")]
        if not built:
            print(f"{svc}: no locally built images")
            continue
        run(["docker", "compose", "-f", str(d / "compose.yml"), "--env-file", str(d / ".env"), "build",
             *[n for n, _ in built]])
        for _, image in built:
            img = image.replace("$$", "$")
            if "${" in img:
                from generate import image_ref
                img = image_ref(svc, image, svc)
            run(["kind", "load", "docker-image", img, "--name", cfg()["K8S_CLUSTER_NAME"]])
            if a.drop_host_copy:
                run(["docker", "rmi", img], check=False)  # kind has its own copy now


def cmd_smoke(a) -> None:
    """Start services with empty data on the test hostnames (*.k8s.local,
    reachable only on this machine, so a fresh app's first-visitor setup
    page is never public), one service at a time: pull its images one by one
    (parallel pulls and unpacks saturated the disks and stalled etcd), apply,
    wait until every workload is ready, check its routes over HTTP, then
    remove it and its images (--keep leaves it running)."""
    c = cfg()
    node = f"{c['K8S_CLUSTER_NAME']}-control-plane"
    ctx = ["kubectl", "--context", f"kind-{c['K8S_CLUSTER_NAME']}", "-n", NAMESPACE]
    names = services(a.services)
    shared = {s["engine"] for svc, s in shared_db_apps().items() if svc in names}
    for engine in sorted(shared):  # the shared servers they need, as homeserver.py starts them
        server = {"postgres": "shared-postgres", "mariadb": "shared-mariadb"}[engine]
        env = load_env(REPO / "services" / server / ".env")
        kubectl("apply", "-f", "-", input=secret_manifest(f"{server}-env", env,
                                                          labels={"k8s.mariadb.com/watch": ""} if engine == "mariadb" else None))
        if engine == "postgres":
            kubectl("apply", "-f", "-", input=basic_auth(f"{server}-superuser", env.get("POSTGRES_USER", "postgres"),
                                                        env.get("POSTGRES_PASSWORD", "")))
        kubectl("apply", "-k", str(K8S / "generated/envs/test" / server))
        kind = "cluster" if engine == "postgres" else "mariadb"
        kubectl("wait", "-n", NAMESPACE, "--for=condition=Ready", f"{kind}/{server}", "--timeout=900s", check=False)
    results = {}
    for svc in names:
        print(f"\n==== {svc}", flush=True)
        wait_for_calm_disk()
        for img in sorted(service_images(svc)):  # one at a time
            ref = img if "/" in img.split(":")[0] or "." in img.split("/")[0] else f"docker.io/library/{img}"
            subprocess.run(["docker", "exec", node, "crictl", "pull", ref], capture_output=True)
        cmd_secrets(argparse.Namespace(services=[svc], env="prod"))  # Secrets only; DOMAIN stays as is
        kubectl("apply", "-k", str(K8S / "generated/envs/test" / svc), check=False)
        results[svc] = smoke_check(svc, ctx, a.timeout)
        print(("OK   " if not results[svc] else "FAIL ") + svc + "".join(f"\n     {n}" for n in results[svc]), flush=True)
        if not a.keep:
            kubectl("delete", "-k", str(K8S / "generated/envs/test" / svc), "--ignore-not-found", "--timeout=300s", check=False)
            wait_for_calm_disk()
            cmd_rmi(argparse.Namespace(services=[svc]))
    print("\n==== smoke results")
    for svc, notes in results.items():
        print(f"{'OK  ' if not notes else 'FAIL'} {svc}")
        for n in notes:
            print(f"     {n}")


def wait_for_calm_disk(limit: float = 20.0, max_wait: int = 1800) -> None:
    """Pause until the host's disk I/O pressure (PSI, avg10) is below limit.
    The test cluster shares this machine's disks with the running services;
    on 2026-10-04 starting Plane while AppFlowy's images were being removed
    drove load to 144 and stalled the API server, so each step waits."""
    psi = Path("/proc/pressure/io")
    if not psi.is_file():
        return
    start = time.time()
    while time.time() - start < max_wait:
        some = psi.read_text().split("\n")[0]
        avg10 = float(some.split("avg10=")[1].split()[0])
        if avg10 < limit:
            return
        print(f"  waiting for the disk to calm down (I/O pressure {avg10:.0f}%)", flush=True)
        time.sleep(20)


def smoke_check(svc: str, ctx: list[str], timeout: int) -> list[str]:
    """Wait for the service's workloads, then check every route's backend:
    through Traefik for open routes; for routes behind authentik (whose
    outpost has no provider for test hostnames) directly at the Service,
    from the edge pod."""
    notes = []
    deadline = time.time() + timeout
    for kind in ("deployment", "statefulset", "daemonset"):
        for o in subprocess.run(ctx + ["get", kind, "-l", f"homeserver/service={svc}", "-o", "name"],
                                capture_output=True, text=True).stdout.split():
            left = max(30, int(deadline - time.time()))
            if subprocess.run(ctx + ["rollout", "status", o, f"--timeout={left}s"], capture_output=True).returncode != 0:
                name = o.split("/", 1)[1]
                state = subprocess.run(ctx + ["get", "pods", "-l", f"app.kubernetes.io/name={name}", "-o",
                                              "jsonpath={range .items[*]}{range .status.initContainerStatuses[*]}init {.name}:{.state.waiting.reason}{.state.terminated.reason} {end}{range .status.containerStatuses[*]}{.name}:{.state.waiting.reason}{.state.terminated.reason} r{.restartCount} {end}{end}"],
                                       capture_output=True, text=True).stdout.strip()
                log = subprocess.run(ctx + ["logs", o, "--all-containers", "--tail=2"], capture_output=True, text=True).stdout.strip().splitlines()
                notes.append(f"{name} NOT READY [{state}] " + " | ".join(l[:160] for l in log[-2:]))
    routes = K8S / "generated/envs/test" / svc / "routes.yaml"
    for r in (yaml.safe_load_all(routes.read_text()) if routes.is_file() else []):
        if not r or r.get("kind") != "HTTPRoute":
            continue
        rules = r["spec"].get("rules", [])
        protected = any(f.get("type") == "ExtensionRef" for rule in rules for f in rule.get("filters", []))
        for h in r["spec"].get("hostnames", []):
            if protected:
                be = rules[-1]["backendRefs"][0]
                code = subprocess.run(ctx + ["exec", "deploy/nginx-plain", "--", "curl", "-s", "-o", "/dev/null", "-m", "15",
                                             "-w", "%{http_code}", f"http://{be['name']}:{be['port']}/"],
                                      capture_output=True, text=True).stdout
                where = f"{be['name']}:{be['port']} (behind the login)"
            else:
                code = subprocess.run(["curl", "-s", "-o", "/dev/null", "-m", "15", "-w", "%{http_code}", "-H", f"Host: {h}",
                                       f"http://127.0.0.1:{cfg()['K8S_HTTP_PORT']}/"], capture_output=True, text=True).stdout
                where = h
            if not code.startswith(("2", "3")) and code not in ("401", "403"):
                notes.append(f"{where} -> HTTP {code}")
    return notes


def service_images(svc: str) -> set[str]:
    """Every image a service's generated manifests use (containers + init)."""
    out = set()
    for f in (K8S / "generated/apps" / svc).glob("*.yaml"):
        for d in yaml.safe_load_all(f.read_text()):
            spec = ((d or {}).get("spec") or {})
            pod = (spec.get("template") or {}).get("spec") or {}
            for c in pod.get("containers", []) + pod.get("initContainers", []):
                out.add(c["image"])
            if spec.get("imageName"):
                out.add(spec["imageName"])
    return out


def cmd_rmi(a) -> None:
    """Remove stopped services' images from the kind node's image store
    (K8S_IMAGES_PATH): not images any running pod still uses."""
    node = f"{cfg()['K8S_CLUSTER_NAME']}-control-plane"
    names = services(a.services)
    # A container that's still shutting down keeps its image in use: wait
    # for the services' pods to be gone first.
    for svc in names:
        subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "-n", NAMESPACE, "wait",
                        "--for=delete", "pod", "-l", f"homeserver/service={svc}", "--timeout=300s"], capture_output=True)
    in_use = set(subprocess.run(["kubectl", "--context", f"kind-{cfg()['K8S_CLUSTER_NAME']}", "get", "pods", "-A", "-o",
                                 "jsonpath={range .items[*]}{range .spec.containers[*]}{.image}{\"\\n\"}{end}"
                                 "{range .spec.initContainers[*]}{.image}{\"\\n\"}{end}{end}"],
                                capture_output=True, text=True).stdout.split())
    wanted = set()
    for svc in names:
        wanted |= service_images(svc)
    for img in sorted(wanted - in_use):
        ref = img if "/" in img.split(":")[0] or "." in img.split("/")[0] else f"docker.io/library/{img}"
        r = subprocess.run(["docker", "exec", node, "crictl", "rmi", ref], capture_output=True, text=True)
        gone = subprocess.run(["docker", "exec", node, "crictl", "inspecti", ref], capture_output=True).returncode != 0
        if gone:
            print(f"removed {img}")
        else:
            err = r.stderr.strip().splitlines()
            print(f"kept    {img}  ({err[-1] if err else 'still present'})")
    kept = sorted(wanted & in_use)
    if kept:
        print("still in use by running pods: " + ", ".join(kept))


def cmd_status(_a) -> None:
    kubectl("get", "pods,svc,pvc,httproute", "-n", NAMESPACE, "-o", "wide", check=False)


def cmd_delete(_a) -> None:
    run(["kind", "delete", "cluster", "--name", cfg()["K8S_CLUSTER_NAME"]])
    print("Host data folders (K8S_FAST_PATH/K8S_BULK_PATH/K8S_IMAGES_PATH) are kept; delete them by hand if wanted.")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("action", choices=["create", "install", "secrets", "apply", "import", "images", "smoke", "rmi", "validate", "status", "delete"])
    ap.add_argument("services", nargs="*")
    ap.add_argument("--env", default="test", choices=["test", "prod"])
    ap.add_argument("--snapshot", help="import: a snapshot folder name (default: the newest)")
    ap.add_argument("--keep", action="store_true", help="smoke: leave the services running")
    ap.add_argument("--drop-host-copy", action="store_true", help="images: remove Docker's copy after loading it into kind")
    ap.add_argument("--timeout", type=int, default=900, help="smoke: seconds to wait for readiness")
    ap.add_argument("--live-db", action="store_true", help="import: own Postgres from the running Compose container (pg_dump)")
    a = ap.parse_args()
    {"create": cmd_create, "install": cmd_install, "secrets": cmd_secrets, "apply": cmd_apply, "import": cmd_import, "validate": cmd_validate, "images": cmd_images, "smoke": cmd_smoke, "rmi": cmd_rmi,
     "status": cmd_status, "delete": cmd_delete}[a.action](a)
    return 0


if __name__ == "__main__":
    sys.exit(main())
