#!/usr/bin/env python3
"""Generate Kubernetes manifests from the Docker Compose definitions.

Compose stays the single source of truth: each services/<svc>/compose.yml
(+ compose.prod.yml), its .env.example, services.json and the nginx-plain
route template are rendered into kubernetes/generated/. Never edit generated
files; edit Compose or kubernetes/overrides/<svc>.yaml and re-run:

    uv run kubernetes/generate.py            # (re)write kubernetes/generated/
    uv run kubernetes/generate.py --check    # exit 1 if generated/ is stale

tests/test_k8s_sync.py runs the --check path, so Compose and Kubernetes can't
drift. Plan and mapping rules: research/kubernetes-compose-parity-plan.md;
step-by-step guide: docs/17-docker-to-kubernetes.md.

Anything the generator can't map safely (a Docker socket, a host path it
doesn't know, a repo folder) raises GenError naming the override to add,
instead of guessing.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import math
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

K8S_DIR = Path(__file__).resolve().parent
REPO = K8S_DIR.parent
SERVICES_DIR = REPO / "services"
GENERATED = K8S_DIR / "generated"
OVERRIDES = K8S_DIR / "overrides"
NAMESPACE = "apps"
GATEWAY = {"name": "homeserver-gateway", "namespace": "infra"}
TEST_DOMAIN = "k8s.local"
HEADER = "# GENERATED by kubernetes/generate.py from services/{svc}/ — do not edit.\n# Change Compose, .env.example or kubernetes/overrides/{svc}.yaml, then re-run it.\n"
ROOT_CONFIGMAP = "homeserver-root"   # root .env (DOMAIN, ...), applied from the host
INJECTED = {"DOMAIN"}                # homeserver.py injects these into every service


class GenError(Exception):
    pass


class _Dumper(yaml.SafeDumper):
    """Plain YAML for review: no &anchors/*aliases for repeated objects."""
    def ignore_aliases(self, data):
        return True


def _str(dumper, data):
    # Multi-line text (my.cnf, scripts) as a readable | block.
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _str)


# ── inputs ────────────────────────────────────────────────────────────────

def load_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text().splitlines():
        m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            out[m[1]] = m[2].strip().strip('"').strip("'")
    return out


VERSIONS = load_env(K8S_DIR / "versions.env")


def base_file(svc: str) -> str:
    return "docker-compose.yml" if svc == "landing" else "compose.yml"


def load_compose(svc: str) -> dict:
    """The service exactly as Compose resolves it (merges, anchors, extends),
    with ${VAR} left unresolved so no .env value is ever inlined."""
    d = SERVICES_DIR / svc
    files = [d / base_file(svc)]
    if (d / "compose.prod.yml").is_file():
        files.append(d / "compose.prod.yml")
    cmd = ["docker", "compose", "--project-directory", str(d)]
    for f in files:
        cmd += ["-f", str(f)]
    cmd += ["config", "--no-interpolate", "--format", "json"]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=d)
    if proc.returncode != 0:
        raise GenError(f"{svc}: docker compose config failed: {proc.stderr.strip()[-300:]}")
    return json.loads(proc.stdout)


def load_overrides(svc: str) -> dict:
    f = OVERRIDES / f"{svc}.yaml"
    return (yaml.safe_load(f.read_text()) or {}) if f.is_file() else {}


def load_scope() -> dict:
    return yaml.safe_load((K8S_DIR / "scope.yaml").read_text()) or {}


NGINX_TEMPLATE = SERVICES_DIR / "nginx-plain/templates/default.conf.template"


def nginx_blocks() -> list[str]:
    """nginx-plain's top-level server { ... } blocks, by brace matching."""
    text = NGINX_TEMPLATE.read_text()
    out = []
    for m in re.finditer(r"^server\s*\{", text, re.M):
        depth, i = 0, m.end() - 1
        while i < len(text):
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            if depth == 0:
                break
            i += 1
        out.append(text[m.start():i + 1])
    return out


def nginx_routes() -> dict[str, list[tuple[str, int]]]:
    """container name -> [(hostname template, port)] from nginx-plain's
    server blocks that proxy `location /` to a container
    (set $upstream http://<container>:<port>). Blocks that serve content
    themselves (root ...; e.g. the Browser Hub) are nginx_sites()."""
    routes: dict[str, list[tuple[str, int]]] = {}
    for block in nginx_blocks():
        names = re.search(r"server_name\s+([^;]+);", block)
        loc = re.search(r"location / \{[^}]*?set \$upstream https?://([a-z0-9-]+):(\d+)", block)
        if not names or not loc:
            continue
        for host in names.group(1).split():
            routes.setdefault(loc.group(1), []).append((host, int(loc.group(2))))
    return routes


def nginx_protected() -> set[str]:
    """Hostname templates nginx-plain puts behind authentik's forward auth."""
    out = set()
    for block in nginx_blocks():
        names = re.search(r"server_name\s+([^;]+);", block)
        if names and "auth_request /outpost.goauthentik.io/auth/nginx;" in block:
            out.update(names.group(1).split())
    return out


def nginx_redirects() -> list[tuple[str, str, int]]:
    """[(hostname, target hostname, status)] for nginx-plain's redirect-only
    server blocks (server_name X; return 301 https://Y$request_uri;), e.g.
    the bare domain -> www."""
    out = []
    for block in nginx_blocks():
        names = re.search(r"server_name\s+([^;]+);", block)
        ret = re.search(r"^\s*return (30[1278]) https://([^$/\s]+(?:\$\{DOMAIN\})?)\$request_uri;", block, re.M)
        if names and ret and "set $upstream" not in block:
            out += [(h, ret.group(2), int(ret.group(1))) for h in names.group(1).split()]
    return out


# ── value helpers ─────────────────────────────────────────────────────────

VAR = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::?-([^}]*))?\}")


def image_ref(svc: str, image: str, where: str) -> str:
    """Images can't use $(VAR) (Kubernetes expands it only in command, args
    and env), so a version kept in .env (twelve-factor) is pinned here from
    .env.example; tests check the real .env agrees."""
    ex = {**load_env(REPO / ".env.example"), **load_env(SERVICES_DIR / svc / ".env.example")}

    def sub(m: re.Match) -> str:
        if m.group(1) in ex:
            return ex[m.group(1)]
        if m.group(2) is not None:
            return m.group(2)
        raise GenError(f"{where}: image variable ${{{m.group(1)}}} isn't in .env.example")
    return VAR.sub(sub, image.replace("$$", "$"))


def k8s_value(text: str, env_keys: set[str], where: str) -> str:
    """Compose ${VAR} / ${VAR:-default} -> Kubernetes $(VAR) (resolved from the
    service's Secret or the root ConfigMap at runtime). A variable that comes
    from neither keeps its Compose default, or fails loudly."""
    def sub(m: re.Match) -> str:
        name, default = m.group(1), m.group(2)
        if name in env_keys or name in INJECTED:
            return f"$({name})"
        if default is not None:
            return default
        raise GenError(f"{where}: ${{{name}}} is in neither .env.example nor the root .env")
    return VAR.sub(sub, text.replace("$$", "$"))


def seconds(v) -> int:
    if v is None:
        return 0
    if isinstance(v, (int, float)):
        return int(v / 1_000_000_000) if v > 10_000 else int(v)
    total, s = 0.0, str(v)
    for num, unit in re.findall(r"([\d.]+)(ms|s|m|h)", s):
        total += float(num) * {"ms": 0.001, "s": 1, "m": 60, "h": 3600}[unit]
    return max(1, math.ceil(total)) if total else 0


def mem(v) -> str:
    s = str(v).strip()
    m = re.match(r"^([\d.]+)\s*([kKmMgG])?[bB]?$", s)
    if not m:
        return s
    n, u = m.group(1), (m.group(2) or "").upper()
    return n + {"K": "Ki", "M": "Mi", "G": "Gi", "": ""}[u]


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", text.lower()).strip("-")[:50]


# ── conversion ────────────────────────────────────────────────────────────

def probe_set(hc: dict | None, env_keys: set[str], where: str) -> dict:
    """Compose healthcheck -> readiness + liveness + startup probes. Readiness
    fails where Docker marks the container unhealthy (after `retries`).
    Liveness uses the same check with a doubled failureThreshold, the
    pattern Kubernetes documents ("the same low-cost endpoint as readiness,
    but with a higher failureThreshold", kubernetes.io/docs/concepts/
    configuration/liveness-readiness-startup-probes): the pod is taken out
    of traffic first and restarted only if it stays unhealthy, so a brief
    database blip doesn't restart every app that checks its database."""
    if not hc or hc.get("disable") or not hc.get("test"):
        return {}
    test = hc["test"]
    if isinstance(test, str):
        test = ["CMD-SHELL", test]
    # Kubernetes doesn't expand $(VAR) in probe commands (only in command,
    # args and env), so variables stay shell ${VAR}, read from the
    # container's environment by sh (ensure_env_defined makes sure they're there).
    if test[0] == "CMD-SHELL":
        cmd = ["sh", "-c", test[1].replace("$$", "$")]
    elif test[0] == "CMD":
        args = [a.replace("$$", "$") for a in test[1:]]
        cmd = ["sh", "-c", " ".join(shlex.quote(a) if "${" not in a else f'"{a}"' for a in args)] if any("${" in a for a in args) else args
    else:
        return {}
    period = seconds(hc.get("interval")) or 30
    timeout = seconds(hc.get("timeout")) or 30
    retries = int(hc.get("retries") or 3)
    base = {"exec": {"command": cmd}, "timeoutSeconds": timeout}
    out = {
        "readinessProbe": {**base, "periodSeconds": period, "failureThreshold": retries},
        "livenessProbe": {**base, "periodSeconds": period, "failureThreshold": retries * 2},
    }
    start = seconds(hc.get("start_period"))
    if start:
        step = seconds(hc.get("start_interval")) or min(period, 10)
        out["startupProbe"] = {**base, "periodSeconds": step,
                               "failureThreshold": math.ceil(start / step) + retries}
    return out


def classify_mount(m: dict, svc: str) -> tuple[str, str]:
    """-> (kind, key): repo-file | repo-dir | data | named | socket | localtime | host"""
    src = str(m.get("source", ""))
    if "DOCKER_SOCKET" in src or src.endswith("docker.sock"):
        return "socket", src
    if src in ("/etc/localtime", "/etc/timezone"):
        return "localtime", src
    if src.startswith("${DATA_ROOT}"):
        return "data", src[len("${DATA_ROOT}"):].strip("/") or "root"
    if src.startswith("${"):
        return "host", src
    if src.startswith(str(REPO) + "/") or src == str(REPO):
        p = Path(src)
        return ("repo-dir" if p.is_dir() else "repo-file"), src
    if src.startswith("/"):
        return "host", src
    return "named", src


def env_list(env: dict, env_keys: set[str], secret: str, has_env_file: bool, where: str) -> list[dict]:
    """Compose substitutes ${VAR} from the service's .env even when the
    container has no env_file. In Kubernetes the value must come from the
    service's Secret: a value that is exactly one .env variable reads that
    key directly; a value with the variable inside a longer string gets just
    that key added first (only when the Secret isn't loaded whole via
    envFrom), then $(VAR) expands it. Loading the whole .env into containers
    that didn't have env_file is avoided on purpose (Zulip refuses to start
    with stray legacy variables)."""
    out: list[dict] = []
    helpers: dict[str, dict] = {}
    for k, v in sorted(env.items()):
        raw = str(v if v is not None else "")
        whole = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", raw)
        if whole and whole[1] in env_keys and not has_env_file:
            out.append({"name": k, "valueFrom": {"secretKeyRef": {"name": secret, "key": whole[1]}}})
            continue
        if not has_env_file:
            for m in VAR.finditer(raw):
                if m[1] in env_keys and m[1] not in helpers and m[1] != k:
                    helpers[m[1]] = {"name": m[1], "valueFrom": {"secretKeyRef": {"name": secret, "key": m[1]}}}
        out.append({"name": k, "value": k8s_value(raw, env_keys, where)})
    return list(helpers.values()) + out


def ensure_env_defined(container: dict, env_keys: set[str], secret: str, has_env_file: bool) -> None:
    """Every variable the container references ($(VAR) in command/args/env, or
    shell ${VAR} in probes) must exist in its environment. Without env_file,
    the .env keys it needs are added one by one from the Secret, first."""
    if has_env_file:
        return
    text = json.dumps({k: container.get(k) for k in ("command", "args", "env", "readinessProbe", "livenessProbe", "startupProbe")})
    names = set(re.findall(r"\$\(([A-Za-z_][A-Za-z0-9_]*)\)", text)) | set(re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)", text))
    have = {e["name"] for e in container.get("env") or []}
    add = [{"name": n, "valueFrom": {"secretKeyRef": {"name": secret, "key": n}}}
           for n in sorted(names) if n in env_keys and n not in have]
    if add:
        container["env"] = add + (container.get("env") or [])


def data_volume(svc: str, kind: str, key: str, mo: dict, ov: dict, pvcs: dict) -> tuple[str, str, str | None]:
    """-> (pod volume name, PVC name, subPath). Compose's ${DATA_ROOT} is one
    folder per service, its subfolders mounted separately: here one PVC
    <svc>-data, each subfolder a subPath, so a one-shot chown of DATA_ROOT
    (the *-permissions containers) covers what the apps mount. Named volumes
    stay one PVC each."""
    store = ov.get("storage") or {}
    if kind == "data":
        pvc, sub, conf = f"{svc}-data", (None if key == "root" else key), store.get("data") or {}
    else:
        pvc, sub, conf = f"{svc}-{slug(key)}", None, store.get(key) or {}
    pvcs.setdefault(pvc, {"size": mo.get("size") or conf.get("size") or "1Gi",
                          "class": mo.get("class") or conf.get("class") or "fast"})
    return f"v-{slug(pvc)}"[:63], pvc, sub


def compose_ports(s: dict) -> tuple[set[int], set[int]]:
    """(tcp, udp) container ports. Long-syntax entries are dicts; ports that
    hold a ${VAR} stay short strings under --no-interpolate
    ("${IP}:53:53/udp"), so the container port is the last field."""
    tcp, udp = set(), set()
    for p in s.get("ports") or []:
        if isinstance(p, dict):
            target, proto = int(p["target"]), p.get("protocol", "tcp")
        else:
            spec, _, proto = str(p).partition("/")
            target, proto = int(spec.rsplit(":", 1)[-1]), proto or "tcp"
        (udp if proto == "udp" else tcp).add(target)
    return tcp, udp


def wait_container(target: str, port: int) -> dict:
    return {
        "name": f"wait-{target}"[:63],
        "image": VERSIONS["WAIT_IMAGE"],
        "command": ["sh", "-c", f"until nc -z -w 2 {target} {port}; do echo waiting for {target}:{port}; sleep 2; done"],
    }


def convert(svc: str) -> dict[str, list[dict]]:
    """-> {filename: [k8s objects]} for one service."""
    compose = load_compose(svc)
    ov = load_overrides(svc)
    ov_c = ov.get("containers") or {}
    env_keys = set(load_env(SERVICES_DIR / svc / ".env.example"))
    services: dict = compose.get("services") or {}
    cname = {n: (s.get("container_name") or n) for n, s in services.items()}
    routes = nginx_routes()
    files: dict[str, list[dict]] = {}
    pvcs: dict[str, dict] = {}
    labels_svc = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}

    # Ports each container listens on (for Services and depends_on waits).
    listen: dict[str, list[int]] = {}
    udp: dict[str, set[int]] = {}
    for n, s in services.items():
        tcp_ports, udp[n] = compose_ports(s)
        ports = sorted(tcp_ports | {int(x) for x in (s.get("expose") or [])})
        ports += [int(p) for p in (ov_c.get(cname[n], {}).get("ports") or []) if int(p) not in ports]
        ports += [p for _, p in routes.get(cname[n], []) if p not in ports]
        listen[n] = sorted(set(ports))

    oneshots = {n for n, s in services.items() if str(s.get("restart", "")).strip('"') in ("no", "on-failure")}

    # A CORE app's own Postgres / MariaDB -> its own operator-run database
    # (CloudNativePG / mariadb-operator), under the container's name.
    own_db = {}
    for n, s in services.items():
        if (ov_c.get(cname[n]) or {}).get("skip"):
            continue
        if cl := own_postgres(svc, n, s, ov):
            listen[n] = [5432]
            dbx = ((ov_c.get(cname[n]) or {}).get("cnpg") or {}).get("database_extensions")
            if dbx:
                spec = pg_owner(svc, s)
                files.setdefault("database.yaml", []).append({
                    "apiVersion": "postgresql.cnpg.io/v1", "kind": "Database",
                    "metadata": {"name": f"{cname[n]}-{slug(spec['db'])}", "labels": labels_svc},
                    "spec": {"name": spec["db"], "owner": spec["user"], "cluster": {"name": cname[n]},
                             "databaseReclaimPolicy": "retain",
                             "extensions": [{"name": e, "ensure": "present"} for e in dbx]}})
        elif cl := own_mariadb(svc, n, s, ov):
            listen[n] = [3306]
        else:
            continue
        if n != cname[n] and cl["kind"] == "Cluster":
            # The Compose service name too (Docker's DNS answers to both).
            cl["spec"]["managed"]["services"]["additional"].append(
                {"selectorType": "rw", "serviceTemplate": {"metadata": {"name": n, "labels": labels_svc}}})
        own_db[n] = cl
        files.setdefault("database.yaml", []).append(cl)

    for n, s in services.items():
        c = cname[n]
        co = ov_c.get(c) or {}
        if co.get("skip"):
            if not co.get("reason"):
                raise GenError(f"{svc}/{c}: overrides skip needs a reason")
            continue
        if n in oneshots and any(n in (o.get("depends_on") or {}) for o in services.values()):
            continue  # becomes an initContainer of whoever depends on it
        if n in own_db:
            continue  # rendered as a CNPG Cluster above
        where = f"{svc}/{c}"
        container: dict = {"name": c, "image": image_ref(svc, s["image"], where)}
        if s.get("entrypoint"):
            ep = s["entrypoint"]
            container["command"] = [k8s_value(a, env_keys, where) for a in (shlex.split(ep) if isinstance(ep, str) else ep)]
        if s.get("command"):
            cm = s["command"]
            container["args"] = [k8s_value(a, env_keys, where) for a in (shlex.split(cm) if isinstance(cm, str) else cm)]
        env_from = [{"configMapRef": {"name": ROOT_CONFIGMAP}}]
        if s.get("env_file"):
            env_from.append({"secretRef": {"name": f"{svc}-env"}})
        container["envFrom"] = env_from
        env = dict(s.get("environment") or {})
        for k, v in (co.get("env") or {}).items():   # Kubernetes-specific values, e.g. a host port -> Service name
            env[k] = v
        if env:
            container["env"] = env_list(env, env_keys, f"{svc}-env", bool(s.get("env_file")), where)
        if listen[n] or udp.get(n):
            container["ports"] = [{"containerPort": p} for p in listen[n]] + \
                [{"containerPort": p, "protocol": "UDP"} for p in sorted(udp.get(n) or [])]
        container.update(probe_set(s.get("healthcheck"), env_keys, where))
        container.update(co.get("probes") or {})
        lim = ((s.get("deploy") or {}).get("resources") or {}).get("limits") or {}
        if lim.get("memory") or s.get("mem_limit"):
            m = mem(lim.get("memory") or s.get("mem_limit"))
            container["resources"] = {"limits": {"memory": m}}
        sc: dict = {}
        if s.get("cap_add"):
            sc["capabilities"] = {"add": sorted(s["cap_add"])}
        if s.get("privileged"):
            sc["privileged"] = True
        if s.get("user"):
            u = str(s["user"]).split(":")
            if u[0].isdigit():
                sc["runAsUser"] = int(u[0])
                if len(u) > 1 and u[1].isdigit():
                    sc["runAsGroup"] = int(u[1])
        if sc:
            container["securityContext"] = sc

        # Volumes
        pod_vols: list[dict] = []
        mounts: list[dict] = []
        files_cm: dict[str, str] = {}
        exec_keys: set[str] = set()
        git_paths: list[tuple[str, str]] = []
        for i, m in enumerate(s.get("volumes") or []):
            kind, key = classify_mount(m, svc)
            ro = bool(m.get("read_only"))
            tgt = m["target"]
            mo = (co.get("mounts") or {}).get(tgt, {})
            if mo.get("skip"):
                continue
            if kind == "localtime":
                continue  # TZ env covers it
            if kind == "socket":
                raise GenError(f"{where}: mounts the Docker socket ({tgt}); Kubernetes has none. "
                               f"Add overrides/{svc}.yaml containers.{c}.mounts.{tgt}.skip (with a reason) or skip the container.")
            if kind == "repo-file":
                p = Path(key)
                rel = p.relative_to(REPO).as_posix()
                k = slug(rel.replace("/", "-").replace(".", "-"))
                files_cm[k] = p.read_text()
                if p.stat().st_mode & 0o111:
                    exec_keys.add(k)  # e.g. entrypoint.sh: ConfigMap files default to 0644
                mounts.append({"name": "files", "mountPath": tgt, "subPath": k, "readOnly": True})
            elif kind == "repo-dir":
                if mo.get("from") != "git":
                    raise GenError(f"{where}: mounts repo folder {key}; add overrides/{svc}.yaml "
                                   f"containers.{c}.mounts.{tgt}: {{from: git}} to clone it with git-sync")
                rel = Path(key).relative_to(REPO).as_posix()
                git_paths.append((rel, tgt))
                mounts.append({"name": "repo", "mountPath": tgt, "subPath": f"repo/{rel}", "readOnly": True})
            elif kind in ("data", "named"):
                vname, pvc, sub = data_volume(svc, kind, key, mo, ov, pvcs)
                if not any(v["name"] == vname for v in pod_vols):
                    pod_vols.append({"name": vname, "persistentVolumeClaim": {"claimName": pvc}})
                mounts.append({"name": vname, "mountPath": tgt, **({"subPath": sub} if sub else {}),
                               **({"readOnly": True} if ro else {})})
            elif mo.get("volume"):
                # A host folder Compose keeps outside DATA_ROOT (cache, uploads,
                # metadata): its own PVC here; cluster.py import can copy the
                # folder in (copy_from: the .env key).
                pvc = f"{svc}-{slug(mo['volume'])}"
                pvcs.setdefault(pvc, {"size": mo.get("size") or "1Gi", "class": mo.get("class") or "fast"})
                vname = f"v-{slug(pvc)}"[:63]
                if not any(v["name"] == vname for v in pod_vols):
                    pod_vols.append({"name": vname, "persistentVolumeClaim": {"claimName": pvc}})
                mounts.append({"name": vname, "mountPath": tgt, **({"readOnly": True} if ro else {})})
            else:
                hp = mo.get("hostPath")
                if not hp:
                    raise GenError(f"{where}: host path {key} -> {tgt}; add overrides/{svc}.yaml "
                                   f"containers.{c}.mounts.{tgt}: {{hostPath: <path on the node>}} or skip it")
                vname = f"h-{slug(tgt)}"[:63]
                pod_vols.append({"name": vname, "hostPath": {"path": hp, "type": "Directory"}})
                mounts.append({"name": vname, "mountPath": tgt, **({"readOnly": True} if ro or mo.get("readOnly") else {})})
        if s.get("devices") and co.get("devices") == "skip" and not co.get("devices_reason"):
            raise GenError(f"{where}: devices: skip needs devices_reason")
        for dev in ([] if co.get("devices") == "skip" else s.get("devices") or []):
            vname = f"dev-{slug(dev['target'])}"[:63]
            pod_vols.append({"name": vname, "hostPath": {"path": dev["source"]}})
            mounts.append({"name": vname, "mountPath": dev["target"]})
        if files_cm:
            cm_name = f"{c}-files"
            files.setdefault("configmaps.yaml", []).append({
                "apiVersion": "v1", "kind": "ConfigMap",
                "metadata": {"name": cm_name, "labels": labels_svc}, "data": dict(sorted(files_cm.items()))})
            pod_vols.append({"name": "files", "configMap": {"name": cm_name, "items": [
                {"key": k, "path": k, "mode": 0o755 if k in exec_keys else 0o644} for k in sorted(files_cm)]}})
        if mounts:
            container["volumeMounts"] = mounts
        ensure_env_defined(container, env_keys, f"{svc}-env", bool(s.get("env_file")))

        init: list[dict] = []
        if git_paths:
            gs = co.get("git") or {}
            init.append({
                "name": "git-clone",
                "image": VERSIONS["GIT_SYNC_IMAGE"],
                "args": ["--repo=" + (gs.get("repo") or "https://github.com/rajubhimani/homeserver.git"),
                         "--ref=" + (gs.get("ref") or "develop"), "--root=/git", "--link=repo",
                         "--depth=1", "--one-time"],
                "volumeMounts": [{"name": "repo", "mountPath": "/git"}],
            })
            pod_vols.append({"name": "repo", "emptyDir": {}})
        for dep, cond in (s.get("depends_on") or {}).items():
            condition = (cond or {}).get("condition", "service_started")
            if dep not in services:
                continue
            if dep in oneshots:
                ds = services[dep]
                ic = {"name": cname[dep], "image": image_ref(svc, ds["image"], where)}
                if ds.get("entrypoint"):
                    ep = ds["entrypoint"]
                    ic["command"] = [k8s_value(a, env_keys, where) for a in (shlex.split(ep) if isinstance(ep, str) else ep)]
                if ds.get("command"):
                    cm = ds["command"]
                    ic["args"] = [k8s_value(a, env_keys, where) for a in (shlex.split(cm) if isinstance(cm, str) else cm)]
                if ds.get("user"):
                    u = str(ds["user"]).split(":")
                    ic["securityContext"] = {"runAsUser": int(u[0]), **({"runAsGroup": int(u[1])} if len(u) > 1 else {})}
                imounts = []
                for dm in ds.get("volumes") or []:
                    dkind, dkey = classify_mount(dm, svc)
                    if dkind not in ("data", "named"):
                        raise GenError(f"{where}: init step {cname[dep]} mounts {dkind} {dkey}; only data/named volumes are supported")
                    vname, pvc, sub = data_volume(svc, dkind, dkey, {}, ov, pvcs)
                    if not any(v["name"] == vname for v in pod_vols):
                        pod_vols.append({"name": vname, "persistentVolumeClaim": {"claimName": pvc}})
                    imounts.append({"name": vname, "mountPath": dm["target"], **({"subPath": sub} if sub else {})})
                if imounts:
                    ic["volumeMounts"] = imounts
                init.append(ic)
            elif condition == "service_healthy":
                if not listen.get(dep):
                    raise GenError(f"{where}: waits for {dep} to be healthy, but {dep} exposes no port; "
                                   f"add overrides/{svc}.yaml containers.{cname[dep]}.ports")
                init.append(wait_container(cname[dep], listen[dep][0]))

        dw = db_wait(svc)
        if dw and n not in oneshots and s.get("env_file"):
            init.insert(0, dw)
        pod: dict = {"enableServiceLinks": False}
        if init:
            pod["initContainers"] = init
        pod["containers"] = [container]
        if s.get("network_mode") == "host":
            pod["hostNetwork"] = True
            pod["dnsPolicy"] = "ClusterFirstWithHostNet"
        if pod_vols:
            pod["volumes"] = pod_vols
        pod.update(co.get("pod") or {})
        labels = {**labels_svc, "app.kubernetes.io/name": c}
        kind = co.get("kind") or ("Job" if n in oneshots else "Deployment")
        obj: dict = {"apiVersion": "batch/v1" if kind == "Job" else "apps/v1", "kind": kind,
                     "metadata": {"name": c, "labels": labels}}
        tmpl = {"metadata": {"labels": labels}, "spec": pod}
        if kind == "Job":
            pod["restartPolicy"] = "OnFailure"
            obj["spec"] = {"backoffLimit": 6, "template": tmpl}
        else:
            spec: dict = {"selector": {"matchLabels": {"app.kubernetes.io/name": c}}, "template": tmpl}
            if kind == "Deployment":
                spec = {"replicas": 1, "revisionHistoryLimit": 3, **spec}
                if any("persistentVolumeClaim" in v for v in pod_vols):
                    spec["strategy"] = {"type": "Recreate"}  # RWO volumes: never two pods at once
            spec.update(co.get("workload") or {})
            obj["spec"] = spec
        files.setdefault("workloads.yaml", []).append(obj)

        for sname in ([c] + ([n] if n != c and re.fullmatch(r"[a-z0-9]([-a-z0-9]*[a-z0-9])?", n) else [])) \
                if (listen[n] or udp.get(n)) and kind != "Job" and not pod.get("hostNetwork") else []:
            # Docker's DNS answers to the container name and the Compose
            # service name; some .env values use the latter (Immich's DB_URL).
            files.setdefault("services.yaml", []).append({
                "apiVersion": "v1", "kind": "Service",
                "metadata": {"name": sname, "labels": labels_svc},
                "spec": {"selector": {"app.kubernetes.io/name": c},
                         "ports": [{"name": f"p{p}", "port": p, "targetPort": p} for p in listen[n]] +
                                  [{"name": f"p{p}-udp", "port": p, "targetPort": p, "protocol": "UDP"}
                                   for p in sorted(udp.get(n) or [])]}})

    for name, spec in sorted(pvcs.items()):
        files.setdefault("storage.yaml", []).append({
            "apiVersion": "v1", "kind": "PersistentVolumeClaim",
            "metadata": {"name": name, "labels": labels_svc},
            "spec": {"accessModes": ["ReadWriteOnce"], "storageClassName": spec["class"],
                     "resources": {"requests": {"storage": spec["size"]}}}})
    return files


AUTHENTIK = {"name": "authentik-server", "port": 9000}
AUTH_MIDDLEWARE = "authentik-forward-auth"


def http_route(name: str, svc: str, hosts_tmpl: list[str], backend: dict, domain: str) -> list[dict]:
    """HTTPRoute(s) for hostnames -> backend. Hosts nginx-plain protects with
    authentik keep that protection: Traefik's ForwardAuth middleware
    (authentik's Traefik guide) on the app, plus /outpost.goauthentik.io/ on
    the same host routed straight to authentik."""
    labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}
    prot = nginx_protected()
    out = []
    for suffix, group in (("", [h for h in hosts_tmpl if h not in prot]),
                          ("-auth" if any(h not in prot for h in hosts_tmpl) else "", [h for h in hosts_tmpl if h in prot])):
        if not group:
            continue
        rules: list[dict] = [{"backendRefs": [backend]}]
        if group[0] in prot:
            rules = [
                {"matches": [{"path": {"type": "PathPrefix", "value": "/outpost.goauthentik.io/"}}],
                 "backendRefs": [dict(AUTHENTIK)]},
                {"filters": [{"type": "ExtensionRef", "extensionRef": {
                    "group": "traefik.io", "kind": "Middleware", "name": AUTH_MIDDLEWARE}}],
                 "backendRefs": [backend]},
            ]
        out.append({"apiVersion": "gateway.networking.k8s.io/v1", "kind": "HTTPRoute",
                    "metadata": {"name": name + suffix, "labels": labels},
                    "spec": {"parentRefs": [GATEWAY],
                             "hostnames": sorted({h.replace("${DOMAIN}", domain) for h in group}),
                             "rules": rules}})
    return out


def authentik_middleware() -> dict:
    """Traefik ForwardAuth -> authentik's embedded outpost, exactly as
    authentik's docs give it (docs.goauthentik.io, proxy provider, Traefik):
    the Kubernetes counterpart of nginx-plain's auth_request."""
    return {
        "apiVersion": "traefik.io/v1alpha1", "kind": "Middleware",
        "metadata": {"name": AUTH_MIDDLEWARE, "labels": {"app.kubernetes.io/part-of": "homeserver",
                                                         "homeserver/service": "authentik"}},
        "spec": {"forwardAuth": {
            "address": f"http://authentik-server.{NAMESPACE}.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik",
            "trustForwardHeader": True,
            "authResponseHeaders": [
                "X-authentik-username", "X-authentik-groups", "X-authentik-entitlements", "X-authentik-email",
                "X-authentik-name", "X-authentik-uid", "X-authentik-jwt", "X-authentik-meta-jwks",
                "X-authentik-meta-outpost", "X-authentik-meta-provider", "X-authentik-meta-app",
                "X-authentik-meta-version"]}},
    }


def route_objects(svc: str, domain: str) -> list[dict]:
    """HTTPRoutes for every container of the service that nginx-plain routes."""
    compose = load_compose(svc)
    ov_c = load_overrides(svc).get("containers") or {}
    out = []
    routes = nginx_routes()
    for n, s in (compose.get("services") or {}).items():
        c = s.get("container_name") or n
        if (ov_c.get(c) or {}).get("skip") or c not in routes:
            continue
        out += http_route(c, svc, sorted({h for h, _ in routes[c]}), {"name": c, "port": routes[c][0][1]}, domain)
        # nginx-plain's redirect-only blocks that point at this container's
        # hostnames -> Gateway API's standard RequestRedirect filter (path and
        # query are kept, like $request_uri).
        own = {h for h, _ in routes[c]}
        redirects = [(f, to, code) for f, to, code in nginx_redirects() if to in own]
        if redirects:
            out.append({
                "apiVersion": "gateway.networking.k8s.io/v1", "kind": "HTTPRoute",
                "metadata": {"name": f"{c}-redirect", "labels": {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}},
                "spec": {"parentRefs": [GATEWAY],
                         "hostnames": sorted({f.replace("${DOMAIN}", domain) for f, _, _ in redirects}),
                         "rules": [{"filters": [{"type": "RequestRedirect", "requestRedirect": {
                             "scheme": "https", "hostname": redirects[0][1].replace("${DOMAIN}", domain),
                             "statusCode": redirects[0][2]}}]}]}})
    return out



# ── databases (phase 2) ───────────────────────────────────────────────────
# The shared servers become operator-managed clusters, provisioned from the
# same services.json "shared_db" entries homeserver.py uses:
#   shared-postgres -> CloudNativePG Cluster + per app DatabaseRole/Database
#   shared-mariadb  -> mariadb-operator MariaDB + per app User/Database/Grant
# Names come from .env.example (tests check the real .env agrees); passwords
# only ever come from Secrets built from the app's .env at apply time.

SHARED = {"postgres": "shared-postgres", "mariadb": "shared-mariadb"}
PORTS = {"postgres": 5432, "mariadb": 3306}


def services_json() -> list[dict]:
    return json.loads((REPO / "services.json").read_text())["services"]


def shared_db_apps() -> dict[str, dict]:
    """slug -> resolved spec {engine, db, user, password_key, dbs} for every
    app on a shared server (names from .env.example, '=literal' honoured)."""
    out = {}
    for s in services_json():
        sd = s.get("shared_db")
        if not sd:
            continue
        ex = load_env(SERVICES_DIR / s["slug"] / ".env.example")
        val = lambda k: k[1:] if k.startswith("=") else ex.get(k, "")  # noqa: E731
        db = val(sd["db"])
        out[s["slug"]] = {"engine": sd["engine"], "db": db, "user": val(sd["user"]),
                          "user_key": sd["user"], "password_key": sd["password"], "dbs": [db] + list(sd.get("extra_dbs") or [])}
    return out


def compose_args(svc: str) -> list[str]:
    s = next(iter(load_compose(svc)["services"].values()))
    cm = s.get("command") or []
    return shlex.split(cm) if isinstance(cm, str) else list(cm)


def compose_limit(svc: str) -> str | None:
    s = next(iter(load_compose(svc)["services"].values()))
    lim = ((s.get("deploy") or {}).get("resources") or {}).get("limits") or {}
    return mem(lim["memory"]) if lim.get("memory") else None


# Settings CloudNativePG manages itself and refuses in `parameters`
# (cloudnative-pg.io/docs/1.30/postgresql_conf, "Fixed parameters").
CNPG_FIXED = {"config_file", "hba_file", "ident_file", "data_directory", "listen_addresses", "port",
              "unix_socket_directories", "unix_socket_group", "unix_socket_permissions", "log_destination",
              "log_directory", "log_filename", "logging_collector", "ssl", "ssl_cert_file", "ssl_key_file",
              "ssl_ca_file", "archive_command", "archive_mode", "restore_command", "recovery_target",
              "primary_conninfo", "hot_standby", "wal_level", "shared_preload_libraries"}


def pg_params(args: list[str]) -> dict[str, str]:
    """postgres -c k=v flags from a Compose command -> CNPG parameters."""
    params = {}
    for i, a in enumerate(args):
        if a == "-c" and i + 1 < len(args) and "=" in args[i + 1]:
            k, v = args[i + 1].split("=", 1)
            if k not in CNPG_FIXED:
                params[k] = v
    return dict(sorted(params.items()))


def cnpg_cluster(name: str, svc: str, params: dict, limit: str | None, size: str, extra: dict) -> dict:
    """A one-instance CloudNativePG Cluster that keeps the Compose container's
    name as its Service (managed.services.additional), so DB_HOST is unchanged."""
    labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}
    extra = dict(extra)
    hba = extra.pop("pg_hba", None)
    pg_extra = extra.pop("postgresql_extra", {})
    return {
        "apiVersion": "postgresql.cnpg.io/v1", "kind": "Cluster",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "instances": 1,
            "imageName": VERSIONS["CNPG_POSTGRES_IMAGE"],
            **extra,
            "postgresql": {"parameters": params, **({"pg_hba": hba} if hba else {}), **pg_extra},
            "storage": {"size": size, "storageClass": "fast"},
            **({"resources": {"limits": {"memory": limit}}} if limit else {}),
            "inheritedMetadata": {"labels": labels},
            "managed": {"services": {"additional": [
                {"selectorType": "rw", "serviceTemplate": {"metadata": {"name": name, "labels": labels}}}]}},
        },
    }


def own_postgres(svc: str, n: str, s: dict, ov: dict) -> dict | None:
    """A CORE app's own `postgres:` container (named by its DB_HOST) -> its own
    CNPG Cluster: database and owner from the same .env keys Compose passes
    (POSTGRES_DB/POSTGRES_USER), password from Secret <svc>-db-owner."""
    c = s.get("container_name") or n
    ex = load_env(SERVICES_DIR / svc / ".env.example")
    co = ((ov.get("containers") or {}).get(c) or {}).get("cnpg")
    if not co and (ex.get("DB_HOST") != c or not re.match(r"(docker\.io/(library/)?)?postgres:", s["image"])):
        return None
    spec = pg_owner(svc, s)
    cm = s.get("command") or []
    lim = ((s.get("deploy") or {}).get("resources") or {}).get("limits") or {}
    size = ((ov.get("storage") or {}).get(c) or {}).get("size", "5Gi")
    extra: dict = {}
    if spec["superuser"]:
        # The app logs in as `postgres` (no POSTGRES_USER in Compose, e.g.
        # Plausible, which creates its own database): CNPG's superuser, with
        # the password from the app's .env.
        extra |= {"enableSuperuserAccess": True, "superuserSecret": {"name": f"{svc}-db-superuser"},
                  "bootstrap": {"initdb": {"database": spec["db"], "owner": spec["db"]}}}
    else:
        # The app's role owns its database but isn't a superuser (unlike the
        # Compose container, where POSTGRES_USER is): the same split managed
        # Postgres (RDS, Cloud SQL, Azure) has.
        extra["bootstrap"] = {"initdb": {"database": spec["db"], "owner": spec["user"],
                                         "secret": {"name": f"{svc}-db-owner"}}}
    if s.get("shm_size"):
        extra["ephemeralVolumesSizeLimit"] = {"shm": mem(s["shm_size"])}
    if co and co.get("extensions"):
        # Extensions as image volumes (CNPG 1.27+), as Immich's own example does.
        extra["postgresql_extra"] = {"shared_preload_libraries": co.get("shared_preload_libraries") or [],
                                     "extensions": co["extensions"]}
    return cnpg_cluster(c, svc, pg_params(shlex.split(cm) if isinstance(cm, str) else list(cm)),
                        mem(lim["memory"]) if lim.get("memory") else None, size, extra)


def pg_owner(svc: str, s: dict) -> dict:
    """{db, user, user_key, password_key, superuser} for an own Postgres from
    the Compose environment it gets (POSTGRES_DB/USER/PASSWORD, as ${KEY} or
    literal), the same values the app connects with."""
    ex = load_env(SERVICES_DIR / svc / ".env.example")
    env = s.get("environment") or {}

    def val(name: str) -> tuple[str | None, str | None]:
        raw = env.get(name)
        if raw is None:
            return (None, ex.get(name)) if name in ex else (None, None)
        m = re.fullmatch(r"\$\{(\w+)\}", str(raw))
        return (m.group(1), ex.get(m.group(1))) if m else (None, str(raw))
    db_key, db = val("POSTGRES_DB")
    user_key, user = val("POSTGRES_USER")
    pw_key, _ = val("POSTGRES_PASSWORD")
    superuser = user in (None, "postgres")
    db = db or user or "postgres"
    if not db or not pw_key:
        raise GenError(f"{svc}: can't resolve the own Postgres database/password from Compose + .env.example")
    return {"db": db, "user": user or "postgres", "user_key": user_key, "password_key": pw_key, "superuser": superuser}


def env_ref(s: dict, *names: str) -> str | None:
    """The .env key a Compose environment entry reads (`X: ${KEY}`), for the
    first of names that's set; a name with no environment entry is the key."""
    env = s.get("environment") or {}
    for name in names:
        if name in env:
            m = re.fullmatch(r"\$\{(\w+)\}", str(env[name]))
            return m.group(1) if m else None
    return None


def own_mariadb(svc: str, n: str, s: dict, ov: dict) -> dict | None:
    """A CORE app's own `mariadb:` container (named by its DB_HOST) -> a
    mariadb-operator MariaDB with the same image, my.cnf flags, database and
    user; passwords from the app's <svc>-env Secret keys Compose reads.
    The operator's Service carries the CR name, so DB_HOST is unchanged."""
    c = s.get("container_name") or n
    ex = load_env(SERVICES_DIR / svc / ".env.example")
    if not re.match(r"(docker\.io/(library/)?)?mariadb:", s["image"]) or ex.get("DB_HOST") != c:
        return None
    root_k = env_ref(s, "MARIADB_ROOT_PASSWORD", "MYSQL_ROOT_PASSWORD")
    db_k, user_k = env_ref(s, "MARIADB_DATABASE", "MYSQL_DATABASE"), env_ref(s, "MARIADB_USER", "MYSQL_USER")
    pw_k = env_ref(s, "MARIADB_PASSWORD", "MYSQL_PASSWORD")
    if not all((root_k, db_k, user_k, pw_k)) or not ex.get(db_k) or not ex.get(user_k):
        raise GenError(f"{svc}/{c}: can't resolve the MariaDB root/database/user/password keys")
    cm = s.get("command") or []
    args = shlex.split(cm) if isinstance(cm, str) else list(cm)
    lim = ((s.get("deploy") or {}).get("resources") or {}).get("limits") or {}
    labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}
    sec = f"{svc}-env"
    return {
        "apiVersion": "k8s.mariadb.com/v1alpha1", "kind": "MariaDB",
        "metadata": {"name": c, "labels": labels},
        "spec": {
            "image": s["image"],
            "rootPasswordSecretKeyRef": {"name": sec, "key": root_k},
            "database": ex[db_k], "username": ex[user_k],
            "passwordSecretKeyRef": {"name": sec, "key": pw_k},
            **({"myCnf": "\n".join(["[mariadb]"] + [a[2:] for a in args if a.startswith("--")]) + "\n"}
               if any(a.startswith("--") for a in args) else {}),
            "storage": {"size": ((ov.get("storage") or {}).get(c) or {}).get("size", "5Gi"), "storageClassName": "fast"},
            **({"resources": {"limits": {"memory": mem(lim["memory"])}}} if lim.get("memory") else {}),
            "inheritMetadata": {"labels": labels},
        },
    }


def own_db_keys(svc: str) -> dict | None:
    """What cluster.py turns into the own Postgres login Secret: pg_owner()
    plus the Secret name (<svc>-db-owner, or <svc>-db-superuser for apps
    that log in as postgres), or None."""
    ov = load_overrides(svc)
    for n, s in (load_compose(svc).get("services") or {}).items():
        if own_postgres(svc, n, s, ov):
            spec = pg_owner(svc, s)
            return {**spec, "secret": f"{svc}-db-{'superuser' if spec['superuser'] else 'owner'}",
                    "container": s.get("container_name") or n}
    return None


def shared_postgres() -> dict[str, list[dict]]:
    svc = "shared-postgres"
    ov = load_overrides(svc)
    params = pg_params(compose_args(svc))
    apps = {a: s for a, s in shared_db_apps().items() if s["engine"] == "postgres"}
    # Each app's login may connect only to its own database(s): the declarative
    # equivalent of homeserver.py's REVOKE ALL ON DATABASE ... FROM PUBLIC,
    # which CNPG can't declare (it doesn't manage privileges).
    hba = [f"host {','.join(s['dbs'])} {s['user']} all scram-sha-256" for _, s in sorted(apps.items())]
    hba.append(f"host all {','.join(sorted({s['user'] for s in apps.values()}))} all reject")
    # The admin login Compose has (POSTGRES_USER=postgres), from a basic-auth
    # Secret cluster.py builds from shared-postgres/.env.
    cluster = cnpg_cluster(svc, svc, params, compose_limit(svc), (ov.get("storage") or {}).get("size", "5Gi"),
                           {"enableSuperuserAccess": True, "superuserSecret": {"name": f"{svc}-superuser"},
                            "pg_hba": hba})
    return {"database.yaml": [cluster]}


def shared_mariadb() -> dict[str, list[dict]]:
    svc = "shared-mariadb"
    ov = load_overrides(svc)
    s = next(iter(load_compose(svc)["services"].values()))
    cnf = ["[mariadb]"] + [a[2:] for a in compose_args(svc) if a.startswith("--")]
    labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}
    lim = compose_limit(svc)
    mdb = {
        "apiVersion": "k8s.mariadb.com/v1alpha1", "kind": "MariaDB",
        "metadata": {"name": svc, "labels": labels},
        "spec": {
            "image": s["image"],  # the exact image Compose runs (official mariadb)
            "rootPasswordSecretKeyRef": {"name": f"{svc}-env", "key": "MARIADB_ROOT_PASSWORD"},
            "myCnf": "\n".join(cnf) + "\n",
            "env": [{"name": "MARIADB_AUTO_UPGRADE", "value": "1"}],  # as in Compose
            "storage": {"size": (ov.get("storage") or {}).get("size", "5Gi"), "storageClassName": "fast"},
            **({"resources": {"limits": {"memory": lim}}} if lim else {}),
            "inheritMetadata": {"labels": labels},
        },
    }
    return {"database.yaml": [mdb]}


def app_database(svc: str) -> list[dict]:
    """Per-app login + database(s) on the shared server, plus nothing else:
    exactly what homeserver.py's provision_shared_db creates under Compose."""
    spec = shared_db_apps().get(svc)
    if not spec:
        return []
    labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}
    server = SHARED[spec["engine"]]
    if spec["engine"] == "postgres":
        objs = [{"apiVersion": "postgresql.cnpg.io/v1", "kind": "DatabaseRole",
                 "metadata": {"name": f"{svc}-role", "labels": labels},
                 "spec": {"cluster": {"name": server}, "name": spec["user"], "login": True,
                          "passwordSecret": {"name": f"{svc}-db-role"},
                          "databaseRoleReclaimPolicy": "retain"}}]
        for db in spec["dbs"]:
            objs.append({"apiVersion": "postgresql.cnpg.io/v1", "kind": "Database",
                         "metadata": {"name": f"{svc}-db-{slug(db)}", "labels": labels},
                         "spec": {"cluster": {"name": server}, "name": db, "owner": spec["user"],
                                  "databaseReclaimPolicy": "retain",
                                  "schemas": [{"name": "public", "owner": spec["user"]}]}})
        return objs
    ref = {"name": server}
    objs = [{"apiVersion": "k8s.mariadb.com/v1alpha1", "kind": "User",
             "metadata": {"name": f"{svc}-user", "labels": labels},
             "spec": {"mariaDbRef": ref, "name": spec["user"], "host": "%",
                      "passwordSecretKeyRef": {"name": f"{svc}-env", "key": spec["password_key"]},
                      # Compose sets no per-user cap; the operator defaults to
                      # 10. 0 = MariaDB's "no limit" (server max-connections applies).
                      "maxUserConnections": 0,
                      "cleanupPolicy": "Skip"}}]
    for db in spec["dbs"]:
        objs.append({"apiVersion": "k8s.mariadb.com/v1alpha1", "kind": "Database",
                     "metadata": {"name": f"{svc}-db-{slug(db)}", "labels": labels},
                     "spec": {"mariaDbRef": ref, "name": db, "characterSet": "utf8mb4",
                              "collate": "utf8mb4_unicode_ci", "cleanupPolicy": "Skip"}})
        objs.append({"apiVersion": "k8s.mariadb.com/v1alpha1", "kind": "Grant",
                     "metadata": {"name": f"{svc}-grant-{slug(db)}", "labels": labels},
                     "spec": {"mariaDbRef": ref, "username": spec["user"], "host": "%",
                              "privileges": ["ALL PRIVILEGES"], "database": db, "table": "*",
                              "cleanupPolicy": "Skip"}})
    return objs


def external_db(svc: str) -> bool:
    """DB_HOST pointing outside the stack (RDS, Cloud SQL, ...): emit no
    database objects for the app, like homeserver.py's shared_db_external()."""
    spec = shared_db_apps().get(svc)
    if not spec:
        return False
    host = load_env(SERVICES_DIR / svc / ".env.example").get("DB_HOST", "")
    return bool(host) and host != SHARED[spec["engine"]]


def db_wait(svc: str) -> dict | None:
    """Apps on a shared server wait for it (homeserver.py starts it first under
    Compose). Host/port come from the app's own DB_HOST/DB_PORT, so an app
    pointed at a managed database waits for that instead."""
    if svc not in shared_db_apps():
        return None
    return {"name": "wait-db", "image": VERSIONS["WAIT_IMAGE"],
            "envFrom": [{"secretRef": {"name": f"{svc}-env"}}],
            "command": ["sh", "-c", 'until nc -z -w 2 "$DB_HOST" "$DB_PORT"; do echo "waiting for $DB_HOST:$DB_PORT"; sleep 2; done']}


# ── nginx-plain's own sites ───────────────────────────────────────────────
AUTH_LINES = re.compile(r"^\s*(auth_request\s|error_page 401 = @goauthentik|auth_request_set \$auth_cookie|"
                        r"add_header Set-Cookie \$auth_cookie).*\n", re.M)


def strip_location(block: str, head: str) -> str:
    """Remove `location <head> { ... }` (brace matched) from a server block."""
    while (i := block.find(f"location {head} {{")) != -1:
        depth, j = 0, block.index("{", i)
        while True:
            depth += {"{": 1, "}": -1}.get(block[j], 0)
            if depth == 0:
                break
            j += 1
        start = block.rfind("\n", 0, i) + 1
        block = block[:start] + block[j + 2:]
    return block


def nginx_plain() -> dict[str, list[dict]]:
    """Traefik replaces nginx-plain's routing. What it can't replace are the
    blocks that serve content themselves (overrides/nginx-plain.yaml sites):
    each runs as a small Deployment of nginx-plain's own image with that
    exact server block. The authentik lines come out (Traefik's ForwardAuth
    does that job in front), upstreams get the in-cluster suffix (nginx's
    resolver doesn't use search domains), and the resolver is kube-dns."""
    svc = "nginx-plain"
    ov = load_overrides(svc)
    s = next(iter(load_compose(svc)["services"].values()))
    text = NGINX_TEMPLATE.read_text()
    header = text[:text.index("\nserver {")]
    blocks = nginx_blocks()
    health = next(b for b in blocks if "server_name _;" in b)
    files: dict[str, list[dict]] = {}
    for site, conf in (ov.get("sites") or {}).items():
        block = next((b for b in blocks if re.search(rf"server_name\s+{re.escape(conf['host'])};", b)), None)
        if not block:
            raise GenError(f"nginx-plain: no server block for {conf['host']}")
        block = AUTH_LINES.sub("", strip_location(strip_location(block, "/outpost.goauthentik.io"), "@goauthentik_proxy_signin"))
        block = re.sub(r"(set \$upstream https?://[a-z0-9-]+)(:\d+;)", rf"\1.{NAMESPACE}.svc.cluster.local\2", block)
        labels = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc, "app.kubernetes.io/name": site}
        html_dir = SERVICES_DIR / svc / conf["html"]
        html = {f.name: f.read_text() for f in sorted(html_dir.iterdir()) if f.is_file()}
        root = re.search(r"root\s+([^;]+);", block).group(1)
        files.setdefault("configmaps.yaml", []).append({
            "apiVersion": "v1", "kind": "ConfigMap", "metadata": {"name": f"{site}-files", "labels": labels},
            "data": {"default.conf.template": "\n".join(
                ln.rstrip() for ln in (header + "\n" + health + "\n\n" + block).splitlines()) + "\n", **html}})
        container = {
            "name": site, "image": s["image"],
            "env": [{"name": "DOMAIN", "valueFrom": {"configMapKeyRef": {"name": ROOT_CONFIGMAP, "key": "DOMAIN"}}},
                    {"name": "NGINX_RESOLVER", "value": "kube-dns.kube-system.svc.cluster.local"}],
            "ports": [{"containerPort": 80}],
            **probe_set(s.get("healthcheck"), set(), f"{svc}/{site}"),
            "volumeMounts": [{"name": "files", "mountPath": "/etc/nginx/templates/default.conf.template",
                              "subPath": "default.conf.template", "readOnly": True}]
            + [{"name": "files", "mountPath": f"{root}/{k}", "subPath": k, "readOnly": True} for k in html],
        }
        files.setdefault("workloads.yaml", []).append({
            "apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": site, "labels": labels},
            "spec": {"replicas": 1, "revisionHistoryLimit": 3,
                     "selector": {"matchLabels": {"app.kubernetes.io/name": site}},
                     "template": {"metadata": {"labels": labels}, "spec": {
                         "enableServiceLinks": False, "containers": [container],
                         "volumes": [{"name": "files", "configMap": {"name": f"{site}-files"}}]}}}})
        files.setdefault("services.yaml", []).append({
            "apiVersion": "v1", "kind": "Service", "metadata": {"name": site, "labels": labels},
            "spec": {"selector": {"app.kubernetes.io/name": site}, "ports": [{"name": "http", "port": 80, "targetPort": 80}]}})
    return files


def nginx_site_routes(domain: str) -> list[dict]:
    out = []
    for site, conf in (load_overrides("nginx-plain").get("sites") or {}).items():
        out += http_route(site, "nginx-plain", [conf["host"]], {"name": site, "port": 80}, domain)
    return out


# ── output ────────────────────────────────────────────────────────────────

def dump(objs: list[dict], svc: str) -> str:
    return HEADER.format(svc=svc) + "---\n".join(yaml.dump(o, Dumper=_Dumper, sort_keys=False, width=120, allow_unicode=True) for o in objs)


def kustomization(resources: list[str], namespace: str | None = NAMESPACE) -> str:
    k = {"apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization"}
    if namespace:
        k["namespace"] = namespace
    k["resources"] = resources
    return "# GENERATED by kubernetes/generate.py — do not edit.\n" + yaml.safe_dump(k, sort_keys=False)


def render(out: Path) -> list[str]:
    scope = load_scope()
    ported = scope.get("ported") or []
    prod_only = set(scope.get("prod_only") or [])
    domain = load_env(REPO / ".env").get("DOMAIN") or load_env(REPO / ".env.example").get("DOMAIN", "example.com")
    written = []
    for svc in ported:
        if svc == "shared-postgres":
            files = shared_postgres()
        elif svc == "shared-mariadb":
            files = shared_mariadb()
        elif svc == "nginx-plain":
            files = nginx_plain()
        else:
            files = convert(svc)
            dbo = app_database(svc)
            if dbo and not external_db(svc):
                files["database.yaml"] = dbo
            if svc == "authentik":
                files["middleware.yaml"] = [authentik_middleware()]
        d = out / "apps" / svc
        d.mkdir(parents=True, exist_ok=True)
        for fname, objs in sorted(files.items()):
            (d / fname).write_text(dump(objs, svc))
        (d / "kustomization.yaml").write_text(kustomization(sorted(files)))
        written.append(svc)
        for env, dom in (("test", TEST_DOMAIN), ("prod", domain)):
            if env == "test" and svc in prod_only:
                continue
            ed = out / "envs" / env / svc
            ed.mkdir(parents=True, exist_ok=True)
            res = [f"../../../apps/{svc}"]
            routes = nginx_site_routes(dom) if svc == "nginx-plain" else route_objects(svc, dom)
            if routes:
                (ed / "routes.yaml").write_text(dump(routes, svc))
                res.append("routes.yaml")
            (ed / "kustomization.yaml").write_text(kustomization(res))
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if kubernetes/generated/ is out of date")
    args = ap.parse_args()
    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmpd = Path(tmp) / "generated"
            render(tmpd)
            if args.check:
                cmp = filecmp.dircmp(tmpd, GENERATED) if GENERATED.is_dir() else None
                stale = _diff(cmp) if cmp else ["(kubernetes/generated/ missing)"]
                if stale:
                    print("kubernetes/generated/ is out of date — run: uv run kubernetes/generate.py\n  " + "\n  ".join(stale))
                    return 1
                print("kubernetes/generated/ is up to date")
                return 0
            if GENERATED.exists():
                shutil.rmtree(GENERATED)
            shutil.copytree(tmpd, GENERATED)
            print(f"wrote {GENERATED.relative_to(REPO)}/")
            return 0
    except GenError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2


def _diff(c: filecmp.dircmp, prefix: str = "") -> list[str]:
    out = [f"{prefix}{x} (only in new)" for x in c.left_only] + [f"{prefix}{x} (stale, removed in new)" for x in c.right_only]
    _, mismatch, errors = filecmp.cmpfiles(c.left, c.right, c.common_files, shallow=False)
    out += [f"{prefix}{x} (differs)" for x in mismatch + errors]
    for sub, sc in c.subdirs.items():
        out += _diff(sc, f"{prefix}{sub}/")
    return out


if __name__ == "__main__":
    sys.exit(main())
