#!/usr/bin/env python3
"""Generate Kubernetes manifests from the Docker Compose definitions.

Compose stays the single source of truth: each services/<svc>/compose.yml
(+ compose.prod.yml), its .env.example, services.json and the nginx-plain
route template are rendered into kubernetes/generated/. Never edit generated
files; edit Compose or kubernetes/overrides/<svc>.yaml and re-run:

    uv run kubernetes/generate.py            # (re)write kubernetes/generated/
    uv run kubernetes/generate.py --check    # exit 1 if generated/ is stale

tests/test_k8s_sync.py runs the --check path, so Compose and Kubernetes can't
drift. Plan and mapping rules: research/kubernetes-compose-parity-plan.md;
step-by-step guide: docs/17-docker-to-kubernetes.md.

Anything the generator can't map safely (a Docker socket, a host path it
doesn't know, a repo folder) raises GenError naming the override to add,
instead of guessing.
"""

from __future__ import annotations

import argparse
import filecmp
import json
import math
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

K8S_DIR = Path(__file__).resolve().parent
REPO = K8S_DIR.parent
SERVICES_DIR = REPO / "services"
GENERATED = K8S_DIR / "generated"
OVERRIDES = K8S_DIR / "overrides"
NAMESPACE = "apps"
GATEWAY = {"name": "homeserver-gateway", "namespace": "infra"}
TEST_DOMAIN = "k8s.local"
HEADER = "# GENERATED by kubernetes/generate.py from services/{svc}/ — do not edit.\n# Change Compose, .env.example or kubernetes/overrides/{svc}.yaml, then re-run it.\n"
ROOT_CONFIGMAP = "homeserver-root"   # root .env (DOMAIN, ...), applied from the host
INJECTED = {"DOMAIN"}                # homeserver.py injects these into every service


class GenError(Exception):
    pass


class _Dumper(yaml.SafeDumper):
    """Plain YAML for review: no &anchors/*aliases for repeated objects."""
    def ignore_aliases(self, data):
        return True


# ── inputs ────────────────────────────────────────────────────────────────

def load_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text().splitlines():
        m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            out[m[1]] = m[2].strip().strip('"').strip("'")
    return out


VERSIONS = load_env(K8S_DIR / "versions.env")


def base_file(svc: str) -> str:
    return "docker-compose.yml" if svc == "landing" else "compose.yml"


def load_compose(svc: str) -> dict:
    """The service exactly as Compose resolves it (merges, anchors, extends),
    with ${VAR} left unresolved so no .env value is ever inlined."""
    d = SERVICES_DIR / svc
    files = [d / base_file(svc)]
    if (d / "compose.prod.yml").is_file():
        files.append(d / "compose.prod.yml")
    cmd = ["docker", "compose", "--project-directory", str(d)]
    for f in files:
        cmd += ["-f", str(f)]
    cmd += ["config", "--no-interpolate", "--format", "json"]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=d)
    if proc.returncode != 0:
        raise GenError(f"{svc}: docker compose config failed: {proc.stderr.strip()[-300:]}")
    return json.loads(proc.stdout)


def load_overrides(svc: str) -> dict:
    f = OVERRIDES / f"{svc}.yaml"
    return (yaml.safe_load(f.read_text()) or {}) if f.is_file() else {}


def load_scope() -> dict:
    return yaml.safe_load((K8S_DIR / "scope.yaml").read_text()) or {}


def nginx_routes() -> dict[str, list[tuple[str, int]]]:
    """container name -> [(hostname template, port)] from nginx-plain's
    server blocks (server_name ... + set $upstream http://<container>:<port>)."""
    text = (SERVICES_DIR / "nginx-plain/templates/default.conf.template").read_text()
    routes: dict[str, list[tuple[str, int]]] = {}
    for block in re.split(r"\n\s*server\s*\{", text):
        names = re.search(r"server_name\s+([^;]+);", block)
        up = re.search(r"set \$upstream https?://([a-z0-9-]+):(\d+)", block)
        if not names or not up:
            continue
        for host in names.group(1).split():
            routes.setdefault(up.group(1), []).append((host, int(up.group(2))))
    return routes


# ── value helpers ─────────────────────────────────────────────────────────

VAR = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::?-([^}]*))?\}")


def k8s_value(text: str, env_keys: set[str], where: str) -> str:
    """Compose ${VAR} / ${VAR:-default} -> Kubernetes $(VAR) (resolved from the
    service's Secret or the root ConfigMap at runtime). A variable that comes
    from neither keeps its Compose default, or fails loudly."""
    def sub(m: re.Match) -> str:
        name, default = m.group(1), m.group(2)
        if name in env_keys or name in INJECTED:
            return f"$({name})"
        if default is not None:
            return default
        raise GenError(f"{where}: ${{{name}}} is in neither .env.example nor the root .env")
    return VAR.sub(sub, text.replace("$$", "$"))


def seconds(v) -> int:
    if v is None:
        return 0
    if isinstance(v, (int, float)):
        return int(v / 1_000_000_000) if v > 10_000 else int(v)
    total, s = 0.0, str(v)
    for num, unit in re.findall(r"([\d.]+)(ms|s|m|h)", s):
        total += float(num) * {"ms": 0.001, "s": 1, "m": 60, "h": 3600}[unit]
    return max(1, math.ceil(total)) if total else 0


def mem(v) -> str:
    s = str(v).strip()
    m = re.match(r"^([\d.]+)\s*([kKmMgG])?[bB]?$", s)
    if not m:
        return s
    n, u = m.group(1), (m.group(2) or "").upper()
    return n + {"K": "Ki", "M": "Mi", "G": "Gi", "": ""}[u]


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", text.lower()).strip("-")[:50]


# ── conversion ────────────────────────────────────────────────────────────

def probe_set(hc: dict | None, env_keys: set[str], where: str) -> dict:
    """Compose healthcheck -> readiness + liveness + startup probes. Docker
    marks a container unhealthy after `retries` failures; Kubernetes restarts
    it at the same point (liveness), which is what the watchdogs used to do."""
    if not hc or hc.get("disable") or not hc.get("test"):
        return {}
    test = hc["test"]
    if isinstance(test, str):
        test = ["CMD-SHELL", test]
    # Kubernetes doesn't expand $(VAR) in probe commands (only in command,
    # args and env), so variables stay shell ${VAR}, read from the
    # container's environment by sh (ensure_env_defined makes sure they're there).
    if test[0] == "CMD-SHELL":
        cmd = ["sh", "-c", test[1].replace("$$", "$")]
    elif test[0] == "CMD":
        args = [a.replace("$$", "$") for a in test[1:]]
        cmd = ["sh", "-c", " ".join(shlex.quote(a) if "${" not in a else f'"{a}"' for a in args)] if any("${" in a for a in args) else args
    else:
        return {}
    period = seconds(hc.get("interval")) or 30
    timeout = seconds(hc.get("timeout")) or 30
    retries = int(hc.get("retries") or 3)
    base = {"exec": {"command": cmd}, "timeoutSeconds": timeout}
    out = {
        "readinessProbe": {**base, "periodSeconds": period, "failureThreshold": retries},
        "livenessProbe": {**base, "periodSeconds": period, "failureThreshold": retries},
    }
    start = seconds(hc.get("start_period"))
    if start:
        step = seconds(hc.get("start_interval")) or min(period, 10)
        out["startupProbe"] = {**base, "periodSeconds": step,
                               "failureThreshold": math.ceil(start / step) + retries}
    return out


def classify_mount(m: dict, svc: str) -> tuple[str, str]:
    """-> (kind, key): repo-file | repo-dir | data | named | socket | localtime | host"""
    src = str(m.get("source", ""))
    if "DOCKER_SOCKET" in src or src.endswith("docker.sock"):
        return "socket", src
    if src in ("/etc/localtime", "/etc/timezone"):
        return "localtime", src
    if src.startswith("${DATA_ROOT}"):
        return "data", src[len("${DATA_ROOT}"):].strip("/") or "root"
    if src.startswith("${"):
        return "host", src
    if src.startswith(str(REPO) + "/") or src == str(REPO):
        p = Path(src)
        return ("repo-dir" if p.is_dir() else "repo-file"), src
    if src.startswith("/"):
        return "host", src
    return "named", src


def env_list(env: dict, env_keys: set[str], secret: str, has_env_file: bool, where: str) -> list[dict]:
    """Compose substitutes ${VAR} from the service's .env even when the
    container has no env_file. In Kubernetes the value must come from the
    service's Secret: a value that is exactly one .env variable reads that
    key directly; a value with the variable inside a longer string gets just
    that key added first (only when the Secret isn't loaded whole via
    envFrom), then $(VAR) expands it. Loading the whole .env into containers
    that didn't have env_file is avoided on purpose (Zulip refuses to start
    with stray legacy variables)."""
    out: list[dict] = []
    helpers: dict[str, dict] = {}
    for k, v in sorted(env.items()):
        raw = str(v if v is not None else "")
        whole = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", raw)
        if whole and whole[1] in env_keys and not has_env_file:
            out.append({"name": k, "valueFrom": {"secretKeyRef": {"name": secret, "key": whole[1]}}})
            continue
        if not has_env_file:
            for m in VAR.finditer(raw):
                if m[1] in env_keys and m[1] not in helpers and m[1] != k:
                    helpers[m[1]] = {"name": m[1], "valueFrom": {"secretKeyRef": {"name": secret, "key": m[1]}}}
        out.append({"name": k, "value": k8s_value(raw, env_keys, where)})
    return list(helpers.values()) + out


def ensure_env_defined(container: dict, env_keys: set[str], secret: str, has_env_file: bool) -> None:
    """Every variable the container references ($(VAR) in command/args/env, or
    shell ${VAR} in probes) must exist in its environment. Without env_file,
    the .env keys it needs are added one by one from the Secret, first."""
    if has_env_file:
        return
    text = json.dumps({k: container.get(k) for k in ("command", "args", "env", "readinessProbe", "livenessProbe", "startupProbe")})
    names = set(re.findall(r"\$\(([A-Za-z_][A-Za-z0-9_]*)\)", text)) | set(re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)", text))
    have = {e["name"] for e in container.get("env") or []}
    add = [{"name": n, "valueFrom": {"secretKeyRef": {"name": secret, "key": n}}}
           for n in sorted(names) if n in env_keys and n not in have]
    if add:
        container["env"] = add + (container.get("env") or [])


def wait_container(target: str, port: int) -> dict:
    return {
        "name": f"wait-{target}"[:63],
        "image": VERSIONS["WAIT_IMAGE"],
        "command": ["sh", "-c", f"until nc -z -w 2 {target} {port}; do echo waiting for {target}:{port}; sleep 2; done"],
    }


def convert(svc: str) -> dict[str, list[dict]]:
    """-> {filename: [k8s objects]} for one service."""
    compose = load_compose(svc)
    ov = load_overrides(svc)
    ov_c = ov.get("containers") or {}
    env_keys = set(load_env(SERVICES_DIR / svc / ".env.example"))
    services: dict = compose.get("services") or {}
    cname = {n: (s.get("container_name") or n) for n, s in services.items()}
    routes = nginx_routes()
    files: dict[str, list[dict]] = {}
    pvcs: dict[str, dict] = {}
    labels_svc = {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}

    # Ports each container listens on (for Services and depends_on waits).
    listen: dict[str, list[int]] = {}
    for n, s in services.items():
        ports = sorted({int(p["target"]) for p in (s.get("ports") or [])} | {int(x) for x in (s.get("expose") or [])})
        ports += [int(p) for p in (ov_c.get(cname[n], {}).get("ports") or []) if int(p) not in ports]
        ports += [p for _, p in routes.get(cname[n], []) if p not in ports]
        listen[n] = sorted(set(ports))

    oneshots = {n for n, s in services.items() if str(s.get("restart", "")).strip('"') in ("no", "on-failure")}

    for n, s in services.items():
        c = cname[n]
        co = ov_c.get(c) or {}
        if co.get("skip"):
            if not co.get("reason"):
                raise GenError(f"{svc}/{c}: overrides skip needs a reason")
            continue
        if n in oneshots and any(n in (o.get("depends_on") or {}) for o in services.values()):
            continue  # becomes an initContainer of whoever depends on it
        where = f"{svc}/{c}"
        container: dict = {"name": c, "image": k8s_value(s["image"], env_keys, where)}
        if s.get("entrypoint"):
            ep = s["entrypoint"]
            container["command"] = [k8s_value(a, env_keys, where) for a in (shlex.split(ep) if isinstance(ep, str) else ep)]
        if s.get("command"):
            cm = s["command"]
            container["args"] = [k8s_value(a, env_keys, where) for a in (shlex.split(cm) if isinstance(cm, str) else cm)]
        env_from = [{"configMapRef": {"name": ROOT_CONFIGMAP}}]
        if s.get("env_file"):
            env_from.append({"secretRef": {"name": f"{svc}-env"}})
        container["envFrom"] = env_from
        env = dict(s.get("environment") or {})
        for k, v in (co.get("env") or {}).items():   # Kubernetes-specific values, e.g. a host port -> Service name
            env[k] = v
        if env:
            container["env"] = env_list(env, env_keys, f"{svc}-env", bool(s.get("env_file")), where)
        if listen[n]:
            container["ports"] = [{"containerPort": p} for p in listen[n]]
        container.update(probe_set(s.get("healthcheck"), env_keys, where))
        container.update(co.get("probes") or {})
        lim = ((s.get("deploy") or {}).get("resources") or {}).get("limits") or {}
        if lim.get("memory") or s.get("mem_limit"):
            m = mem(lim.get("memory") or s.get("mem_limit"))
            container["resources"] = {"limits": {"memory": m}}
        sc: dict = {}
        if s.get("cap_add"):
            sc["capabilities"] = {"add": sorted(s["cap_add"])}
        if s.get("privileged"):
            sc["privileged"] = True
        if s.get("user"):
            u = str(s["user"]).split(":")
            if u[0].isdigit():
                sc["runAsUser"] = int(u[0])
                if len(u) > 1 and u[1].isdigit():
                    sc["runAsGroup"] = int(u[1])
        if sc:
            container["securityContext"] = sc

        # Volumes
        pod_vols: list[dict] = []
        mounts: list[dict] = []
        files_cm: dict[str, str] = {}
        exec_keys: set[str] = set()
        git_paths: list[tuple[str, str]] = []
        for i, m in enumerate(s.get("volumes") or []):
            kind, key = classify_mount(m, svc)
            ro = bool(m.get("read_only"))
            tgt = m["target"]
            mo = (co.get("mounts") or {}).get(tgt, {})
            if mo.get("skip"):
                continue
            if kind == "localtime":
                continue  # TZ env covers it
            if kind == "socket":
                raise GenError(f"{where}: mounts the Docker socket ({tgt}); Kubernetes has none. "
                               f"Add overrides/{svc}.yaml containers.{c}.mounts.{tgt}.skip (with a reason) or skip the container.")
            if kind == "repo-file":
                p = Path(key)
                rel = p.relative_to(REPO).as_posix()
                k = slug(rel.replace("/", "-").replace(".", "-"))
                files_cm[k] = p.read_text()
                if p.stat().st_mode & 0o111:
                    exec_keys.add(k)  # e.g. entrypoint.sh: ConfigMap files default to 0644
                mounts.append({"name": "files", "mountPath": tgt, "subPath": k, "readOnly": True})
            elif kind == "repo-dir":
                if mo.get("from") != "git":
                    raise GenError(f"{where}: mounts repo folder {key}; add overrides/{svc}.yaml "
                                   f"containers.{c}.mounts.{tgt}: {{from: git}} to clone it with git-sync")
                rel = Path(key).relative_to(REPO).as_posix()
                git_paths.append((rel, tgt))
                mounts.append({"name": "repo", "mountPath": tgt, "subPath": f"repo/{rel}", "readOnly": True})
            elif kind in ("data", "named"):
                pvc = f"{svc}-{slug(key)}"
                pvcs.setdefault(pvc, {"size": mo.get("size") or (ov.get("storage") or {}).get(key, {}).get("size") or "1Gi",
                                      "class": mo.get("class") or "fast"})
                vname = f"v-{slug(key)}"[:63]
                if not any(v["name"] == vname for v in pod_vols):
                    pod_vols.append({"name": vname, "persistentVolumeClaim": {"claimName": pvc}})
                mounts.append({"name": vname, "mountPath": tgt, **({"readOnly": True} if ro else {})})
            else:
                hp = mo.get("hostPath")
                if not hp:
                    raise GenError(f"{where}: host path {key} -> {tgt}; add overrides/{svc}.yaml "
                                   f"containers.{c}.mounts.{tgt}: {{hostPath: <path on the node>}} or skip it")
                vname = f"h-{slug(tgt)}"[:63]
                pod_vols.append({"name": vname, "hostPath": {"path": hp}})
                mounts.append({"name": vname, "mountPath": tgt, **({"readOnly": True} if ro else {})})
        if s.get("devices") and co.get("devices") == "skip" and not co.get("devices_reason"):
            raise GenError(f"{where}: devices: skip needs devices_reason")
        for dev in ([] if co.get("devices") == "skip" else s.get("devices") or []):
            vname = f"dev-{slug(dev['target'])}"[:63]
            pod_vols.append({"name": vname, "hostPath": {"path": dev["source"]}})
            mounts.append({"name": vname, "mountPath": dev["target"]})
        if files_cm:
            cm_name = f"{c}-files"
            files.setdefault("configmaps.yaml", []).append({
                "apiVersion": "v1", "kind": "ConfigMap",
                "metadata": {"name": cm_name, "labels": labels_svc}, "data": dict(sorted(files_cm.items()))})
            pod_vols.append({"name": "files", "configMap": {"name": cm_name, "items": [
                {"key": k, "path": k, "mode": 0o755 if k in exec_keys else 0o644} for k in sorted(files_cm)]}})
        if mounts:
            container["volumeMounts"] = mounts
        ensure_env_defined(container, env_keys, f"{svc}-env", bool(s.get("env_file")))

        init: list[dict] = []
        if git_paths:
            gs = co.get("git") or {}
            init.append({
                "name": "git-clone",
                "image": VERSIONS["GIT_SYNC_IMAGE"],
                "args": ["--repo=" + (gs.get("repo") or "https://github.com/rajubhimani/homeserver.git"),
                         "--ref=" + (gs.get("ref") or "develop"), "--root=/git", "--link=repo",
                         "--depth=1", "--one-time"],
                "volumeMounts": [{"name": "repo", "mountPath": "/git"}],
            })
            pod_vols.append({"name": "repo", "emptyDir": {}})
        for dep, cond in (s.get("depends_on") or {}).items():
            condition = (cond or {}).get("condition", "service_started")
            if dep not in services:
                continue
            if dep in oneshots:
                ds = services[dep]
                ic = {"name": cname[dep], "image": k8s_value(ds["image"], env_keys, where)}
                if ds.get("entrypoint"):
                    ep = ds["entrypoint"]
                    ic["command"] = [k8s_value(a, env_keys, where) for a in (shlex.split(ep) if isinstance(ep, str) else ep)]
                if ds.get("command"):
                    cm = ds["command"]
                    ic["args"] = [k8s_value(a, env_keys, where) for a in (shlex.split(cm) if isinstance(cm, str) else cm)]
                init.append(ic)
            elif condition == "service_healthy":
                if not listen.get(dep):
                    raise GenError(f"{where}: waits for {dep} to be healthy, but {dep} exposes no port; "
                                   f"add overrides/{svc}.yaml containers.{cname[dep]}.ports")
                init.append(wait_container(cname[dep], listen[dep][0]))

        pod: dict = {"enableServiceLinks": False}
        if init:
            pod["initContainers"] = init
        pod["containers"] = [container]
        if s.get("network_mode") == "host":
            pod["hostNetwork"] = True
            pod["dnsPolicy"] = "ClusterFirstWithHostNet"
        if pod_vols:
            pod["volumes"] = pod_vols
        labels = {**labels_svc, "app.kubernetes.io/name": c}
        kind = co.get("kind") or ("Job" if n in oneshots else "Deployment")
        obj: dict = {"apiVersion": "batch/v1" if kind == "Job" else "apps/v1", "kind": kind,
                     "metadata": {"name": c, "labels": labels}}
        tmpl = {"metadata": {"labels": labels}, "spec": pod}
        if kind == "Job":
            pod["restartPolicy"] = "OnFailure"
            obj["spec"] = {"backoffLimit": 6, "template": tmpl}
        else:
            spec: dict = {"selector": {"matchLabels": {"app.kubernetes.io/name": c}}, "template": tmpl}
            if kind == "Deployment":
                spec = {"replicas": 1, "revisionHistoryLimit": 3, **spec}
                if any("persistentVolumeClaim" in v for v in pod_vols):
                    spec["strategy"] = {"type": "Recreate"}  # RWO volumes: never two pods at once
            obj["spec"] = spec
        files.setdefault("workloads.yaml", []).append(obj)

        if listen[n] and kind != "Job" and not pod.get("hostNetwork"):
            files.setdefault("services.yaml", []).append({
                "apiVersion": "v1", "kind": "Service",
                "metadata": {"name": c, "labels": labels_svc},
                "spec": {"selector": {"app.kubernetes.io/name": c},
                         "ports": [{"name": f"p{p}", "port": p, "targetPort": p} for p in listen[n]]}})

    for name, spec in sorted(pvcs.items()):
        files.setdefault("storage.yaml", []).append({
            "apiVersion": "v1", "kind": "PersistentVolumeClaim",
            "metadata": {"name": name, "labels": labels_svc},
            "spec": {"accessModes": ["ReadWriteOnce"], "storageClassName": spec["class"],
                     "resources": {"requests": {"storage": spec["size"]}}}})
    return files


def route_objects(svc: str, domain: str) -> list[dict]:
    """HTTPRoutes for every container of the service that nginx-plain routes."""
    compose = load_compose(svc)
    ov_c = load_overrides(svc).get("containers") or {}
    out = []
    routes = nginx_routes()
    for n, s in (compose.get("services") or {}).items():
        c = s.get("container_name") or n
        if (ov_c.get(c) or {}).get("skip") or c not in routes:
            continue
        hosts = sorted({h.replace("${DOMAIN}", domain) for h, _ in routes[c]})
        port = routes[c][0][1]
        out.append({
            "apiVersion": "gateway.networking.k8s.io/v1", "kind": "HTTPRoute",
            "metadata": {"name": c, "labels": {"app.kubernetes.io/part-of": "homeserver", "homeserver/service": svc}},
            "spec": {"parentRefs": [GATEWAY], "hostnames": hosts,
                     "rules": [{"backendRefs": [{"name": c, "port": port}]}]}})
    return out


# ── output ────────────────────────────────────────────────────────────────

def dump(objs: list[dict], svc: str) -> str:
    return HEADER.format(svc=svc) + "---\n".join(yaml.dump(o, Dumper=_Dumper, sort_keys=False, width=120) for o in objs)


def kustomization(resources: list[str], namespace: str | None = NAMESPACE) -> str:
    k = {"apiVersion": "kustomize.config.k8s.io/v1beta1", "kind": "Kustomization"}
    if namespace:
        k["namespace"] = namespace
    k["resources"] = resources
    return "# GENERATED by kubernetes/generate.py — do not edit.\n" + yaml.safe_dump(k, sort_keys=False)


def render(out: Path) -> list[str]:
    scope = load_scope()
    ported = scope.get("ported") or []
    prod_only = set(scope.get("prod_only") or [])
    domain = load_env(REPO / ".env").get("DOMAIN") or load_env(REPO / ".env.example").get("DOMAIN", "example.com")
    written = []
    for svc in ported:
        files = convert(svc)
        d = out / "apps" / svc
        d.mkdir(parents=True, exist_ok=True)
        for fname, objs in sorted(files.items()):
            (d / fname).write_text(dump(objs, svc))
        (d / "kustomization.yaml").write_text(kustomization(sorted(files)))
        written.append(svc)
        for env, dom in (("test", TEST_DOMAIN), ("prod", domain)):
            if env == "test" and svc in prod_only:
                continue
            ed = out / "envs" / env / svc
            ed.mkdir(parents=True, exist_ok=True)
            res = [f"../../../apps/{svc}"]
            routes = route_objects(svc, dom)
            if routes:
                (ed / "routes.yaml").write_text(dump(routes, svc))
                res.append("routes.yaml")
            (ed / "kustomization.yaml").write_text(kustomization(res))
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if kubernetes/generated/ is out of date")
    args = ap.parse_args()
    try:
        with tempfile.TemporaryDirectory() as tmp:
            tmpd = Path(tmp) / "generated"
            render(tmpd)
            if args.check:
                cmp = filecmp.dircmp(tmpd, GENERATED) if GENERATED.is_dir() else None
                stale = _diff(cmp) if cmp else ["(kubernetes/generated/ missing)"]
                if stale:
                    print("kubernetes/generated/ is out of date — run: uv run kubernetes/generate.py\n  " + "\n  ".join(stale))
                    return 1
                print("kubernetes/generated/ is up to date")
                return 0
            if GENERATED.exists():
                shutil.rmtree(GENERATED)
            shutil.copytree(tmpd, GENERATED)
            print(f"wrote {GENERATED.relative_to(REPO)}/")
            return 0
    except GenError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2


def _diff(c: filecmp.dircmp, prefix: str = "") -> list[str]:
    out = [f"{prefix}{x} (only in new)" for x in c.left_only] + [f"{prefix}{x} (stale, removed in new)" for x in c.right_only]
    _, mismatch, errors = filecmp.cmpfiles(c.left, c.right, c.common_files, shallow=False)
    out += [f"{prefix}{x} (differs)" for x in mismatch + errors]
    for sub, sc in c.subdirs.items():
        out += _diff(sc, f"{prefix}{sub}/")
    return out


if __name__ == "__main__":
    sys.exit(main())
